// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         first: 42,
 *         last: 42,
 *         resource_id: "resource_id"
 *     }
 */
export interface ListReactionsRequest {
    /** Returns the elements in the list that come after the specified cursor. */
    after?: string;
    /** Returns the elements in the list that come before the specified cursor. */
    before?: string;
    /** Returns the first _n_ elements from the list. */
    first?: number;
    /** Returns the last _n_ elements from the list. */
    last?: number;
    /** The unique identifier of the message or forum post to list reactions for. */
    resource_id: string;
}
