// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "reac_xxxxxxxxxxxxxxxxxxxxxx"
 *     }
 */
export interface RetrieveReactionsRequest {
    /** The unique identifier of the reaction to retrieve. */
    id: string;
}
