// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {
 *         action: "allow",
 *         conditions: {
 *             all: [{
 *                     field: "risk_score",
 *                     operator: "gte",
 *                     value: 70
 *                 }]
 *         },
 *         name: "Review risky cards"
 *     }
 */
export interface CreatePaymentRulesRequest {
    /** The account to create the rule on. Defaults to the account the request is acting for. */
    account_id?: string;
    /** What this account's rule requests when every condition matches. One applicable account-rule action wins, in this order: `allow`, `block`, `review`, `enforce_3ds`. An `allow` overrides this account's other rules, never Whop's own fraud controls. A `review` requests authorization without capture for an eligible on-session card payment through Whop Payments. Automatic capture is scheduled for 48 hours after authorization; capture or void the payment before then to decide sooner. Capture may complete later or fail. Review is skipped for unsupported methods, off-session payments, and payments already configured for manual capture. An `enforce_3ds` is skipped when the account rule cannot apply a challenge. Other 3DS requirements still apply. */
    action: CreatePaymentRulesRequest.Action;
    /** The conditions a payment is matched against. Up to 10 conditions, and 8 KiB once serialized. */
    conditions: CreatePaymentRulesRequest.Conditions;
    /** Custom string-to-string values for your integration. Maximum 50 keys, 40 characters per key, 500 characters per value. */
    metadata?: Record<string, string>;
    /** A name for this rule. Up to 255 characters. */
    name: string;
}

export namespace CreatePaymentRulesRequest {
    /** What this account's rule requests when every condition matches. One applicable account-rule action wins, in this order: `allow`, `block`, `review`, `enforce_3ds`. An `allow` overrides this account's other rules, never Whop's own fraud controls. A `review` requests authorization without capture for an eligible on-session card payment through Whop Payments. Automatic capture is scheduled for 48 hours after authorization; capture or void the payment before then to decide sooner. Capture may complete later or fail. Review is skipped for unsupported methods, off-session payments, and payments already configured for manual capture. An `enforce_3ds` is skipped when the account rule cannot apply a challenge. Other 3DS requirements still apply. */
    export const Action = {
        Allow: "allow",
        Block: "block",
        Review: "review",
        Enforce3Ds: "enforce_3ds",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];

    /**
     * The conditions a payment is matched against. Up to 10 conditions, and 8 KiB once serialized.
     */
    export interface Conditions {
        all: Conditions.All.Item[];
    }

    export namespace Conditions {
        export type All = All.Item[];

        export namespace All {
            export interface Item {
                /** The payment attribute this condition reads. */
                field: Item.Field;
                /** How the payment attribute is compared to the value. */
                operator: Item.Operator;
                value: Whop.PaymentRuleConditionValue;
            }

            export namespace Item {
                /** The payment attribute this condition reads. */
                export const Field = {
                    RiskScore: "risk_score",
                    AmountInUsd: "amount_in_usd",
                    CardCountry: "card_country",
                    CustomerEmail: "customer_email",
                    IpAddress: "ip_address",
                } as const;
                export type Field = (typeof Field)[keyof typeof Field];
                /** How the payment attribute is compared to the value. */
                export const Operator = {
                    Eq: "eq",
                    Neq: "neq",
                    Gt: "gt",
                    Gte: "gte",
                    Lt: "lt",
                    Lte: "lte",
                    In: "in",
                    NotIn: "not_in",
                    Contains: "contains",
                    StartsWith: "starts_with",
                    EndsWith: "ends_with",
                    InCidr: "in_cidr",
                } as const;
                export type Operator = (typeof Operator)[keyof typeof Operator];
            }
        }
    }
}
