// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeletePaymentRulesRequest {
    /** The payment rule ID. */
    id: string;
}
