// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListDisputesRequest {
    /** Only disputes filed against this account (`biz_` tag). Omit it to cover every account you can read. */
    account_id?: string;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
    /** Number of results to return from the end of the range. */
    last?: number;
    /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
    before?: string;
    /** The field to sort disputes by. */
    order?: Whop.ListDisputesRequestOrder;
    /** Sort direction. */
    direction?: Whop.ListDisputesRequestDirection;
    /** Only disputes in these statuses. Repeat the parameter to pass several — one paginated list covers all of them. Inquiries match only the `warning_` statuses. A `needs_response` dispute whose evidence deadline has passed reports and filters as `under_review` instead. */
    status?: Whop.ListDisputesRequestStatusItem | Whop.ListDisputesRequestStatusItem[];
    /** Only disputes in this three-letter ISO currency. */
    currency?: string;
    /** Only disputes opened before this ISO 8601 timestamp. */
    created_before?: string;
    /** Only disputes opened after this ISO 8601 timestamp. */
    created_after?: string;
}
