// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "dspt_xxxxxxxxxxxxx"
 *     }
 */
export interface SubmitEvidenceDisputeRequest {
    /** The unique identifier of the dispute to submit to the payment processor for review. */
    id: string;
}
