// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "wdrl_xxxxxxxxxxxxx"
 *     }
 */
export interface RetrieveWithdrawalsRequest {
    /** The unique identifier of the withdrawal to retrieve. */
    id: string;
}
