// This file was auto-generated by Fern from our API Definition.

export const ListExternalAccountsRequestOrder = {
    DisplayOrder: "display_order",
    CreatedAt: "created_at",
} as const;
export type ListExternalAccountsRequestOrder =
    (typeof ListExternalAccountsRequestOrder)[keyof typeof ListExternalAccountsRequestOrder];
