// This file was auto-generated by Fern from our API Definition.

/**
 * Result from a stats query (raw, metric, or SQL).
 */
export interface MetricStatsResponse {
    /** Column names in the order they appear in each data row. */
    columns: string[] | null;
    /** Array of data rows, where each row is an array of values matching the columns order. */
    data: Record<string, unknown>[] | null;
    /** Debug information including engine and SQL. */
    debug: MetricStatsResponse.Debug | null;
    /** The node path that was queried. */
    node: string | null;
    /** Pagination information. */
    pagination: MetricStatsResponse.Pagination | null;
    /** The typename of this object */
    typename: MetricStatsResponse.Typename;
}

export namespace MetricStatsResponse {
    /**
     * Debug information including engine and SQL.
     */
    export interface Debug {
        /** The query engine used. */
        engine: string | null;
        /** Unique request identifier for debugging. */
        request_id: string | null;
        /** The generated SQL query (with IDs sanitized). */
        sql: string | null;
    }

    /**
     * Pagination information.
     */
    export interface Pagination {
        /** Cursor for the next page of results. */
        next_cursor: string | null;
    }

    /** The typename of this object */
    export const Typename = {
        Result: "Result",
    } as const;
    export type Typename = (typeof Typename)[keyof typeof Typename];
}
