// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PartnersSocialAccountsRequest {
    /** The brand's Instagram social account (a sacc_ identifier). */
    id: string;
    /** The Account (biz_ identifier) that advertises as the Instagram account. An account-scoped API key may omit this to default to its own account. */
    account_id?: string;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
}
