// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../index.js";

export interface ListPromoCodesResponse {
    data: Whop.PromoCodeListItem[];
    page_info: ListPromoCodesResponse.PageInfo;
}

export namespace ListPromoCodesResponse {
    export interface PageInfo {
        end_cursor: string | null;
        has_next_page: boolean;
        has_previous_page: boolean;
        start_cursor: string | null;
    }
}
