// This file was auto-generated by Fern from our API Definition.

export const ListPromoCodesRequestStatus = {
    Active: "active",
    Inactive: "inactive",
    Archived: "archived",
    Expired: "expired",
} as const;
export type ListPromoCodesRequestStatus =
    (typeof ListPromoCodesRequestStatus)[keyof typeof ListPromoCodesRequestStatus];
