// This file was auto-generated by Fern from our API Definition.

export const ListTeamMembersRequestRole = {
    Owner: "owner",
    Admin: "admin",
    SalesManager: "sales_manager",
    Moderator: "moderator",
    Advertiser: "advertiser",
    AppManager: "app_manager",
    Support: "support",
    Manager: "manager",
    Workforce: "workforce",
    Custom: "custom",
} as const;
export type ListTeamMembersRequestRole = (typeof ListTeamMembersRequestRole)[keyof typeof ListTeamMembersRequestRole];
