// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListDeliveriesWebhooksRequest {
    /** Webhook ID, prefixed `hook_`. */
    id: string;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
}
