// This file was auto-generated by Fern from our API Definition.

export const ListDisputesRequestOrder = {
    CreatedAt: "created_at",
    Amount: "amount",
    EvidenceDueAt: "evidence_due_at",
} as const;
export type ListDisputesRequestOrder = (typeof ListDisputesRequestOrder)[keyof typeof ListDisputesRequestOrder];
