// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Whop from "../../../index.js";

export declare namespace DisputeAlertsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * A Dispute alert is an early warning from a card issuer that a settled payment is being questioned, ahead of any chargeback. `type` separates fraud reports (`early_fraud_warning`), pre-dispute notices (`dispute_alert`), and Visa RDR cases the network already closed by refunding (`rapid_dispute_resolution`).
 *
 * Use the Dispute alerts API to list alerts for an account, filter them by type or payment, and read `actionable` to see whether refunding can still avoid the chargeback.
 */
export class DisputeAlertsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DisputeAlertsClient.Options>;

    constructor(options: DisputeAlertsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists the dispute alerts and early fraud warnings across the accounts you can read.
     *
     * @param {Whop.ListDisputeAlertsRequest} request
     * @param {DisputeAlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.disputeAlerts.list()
     */
    public async list(
        request: Whop.ListDisputeAlertsRequest = {},
        requestOptions?: DisputeAlertsClient.RequestOptions,
    ): Promise<core.Page<Whop.DisputeAlert, Whop.ListDisputeAlertsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Whop.ListDisputeAlertsRequest,
            ): Promise<core.WithRawResponse<Whop.ListDisputeAlertsResponse>> => {
                const {
                    account_id: accountId,
                    payment_id: paymentId,
                    type: type_,
                    first,
                    after,
                    last,
                    before,
                    order,
                    direction,
                    created_before: createdBefore,
                    created_after: createdAfter,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    account_id: accountId,
                    payment_id: paymentId,
                    type: type_ != null ? type_ : undefined,
                    first,
                    after,
                    last,
                    before,
                    order: order != null ? order : undefined,
                    direction: direction != null ? direction : undefined,
                    created_before: createdBefore,
                    created_after: createdAfter,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        "Api-Version-Date":
                            requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-21-1",
                        "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.WhopEnvironment.Default,
                        "dispute_alerts",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Whop.ListDisputeAlertsResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                        case 401:
                            throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                        case 403:
                            throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        default:
                            throw new errors.WhopError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/dispute_alerts");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Whop.DisputeAlert, Whop.ListDisputeAlertsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.page_info.end_cursor != null &&
                !(typeof response?.page_info.end_cursor === "string" && response?.page_info.end_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "after", response?.page_info.end_cursor));
            },
        });
    }

    /**
     * Retrieves a single dispute alert or early fraud warning by ID.
     *
     * @param {Whop.RetrieveDisputeAlertsRequest} request
     * @param {DisputeAlertsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.disputeAlerts.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Whop.RetrieveDisputeAlertsRequest,
        requestOptions?: DisputeAlertsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.DisputeAlert> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Whop.RetrieveDisputeAlertsRequest,
        requestOptions?: DisputeAlertsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.DisputeAlert>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-21-1",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `dispute_alerts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.DisputeAlert, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/dispute_alerts/{id}");
    }
}
