configured_endpoints: 135
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-945f5c3be0565c15e8d90d08abc363442dcdc5d97f0e09bb5da6de4a2bad4795.yml
openapi_spec_hash: ae66f8bc41dc8a1aad1032043ea3ec1c
config_hash: c4e43bac321badafc3ba52b6c6c4e646
