configured_endpoints: 28
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-0e7a392df535ebadf46d2bc34d7f7db1efcc0c7f0268f4199aff28b0cdbe5180.yml
openapi_spec_hash: 8d9bdbef925547b8f843a2c09cbc26d5
config_hash: ed4c0003b39b0b6af6de175e054b9ed7
