configured_endpoints: 171
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-1b994c7d42f111654c3ec3cc8b3a77b5dbd53358b3c5ba67d2cc5eddff7ceeb9.yml
openapi_spec_hash: 323a7375bb67d9444dfb9f16ed58ff7d
config_hash: 1e7e54fcdf77e10c5e3a52f0ffde958d
