configured_endpoints: 135
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-c178f42b4148b18ec79eff90b69cbf0639d866e5cd8d12d88bdaa6dfce0487e2.yml
openapi_spec_hash: 67d0a18a88f598ea5777aaedf0be6eca
config_hash: c4e43bac321badafc3ba52b6c6c4e646
