configured_endpoints: 171
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-ae8f56c0ac4f6aabab3b143eac7c973da5b0ee2daad9a835d76cb61720d5863f.yml
openapi_spec_hash: a14ea8fd8e5de7f0ba5c354d405bc255
config_hash: fabb4feac489d97eb29d8f132176f648
