configured_endpoints: 81
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-cc2c9659646bfa86078ad117aecdb4ad84f1dd6568cf30feb1fcbea0d99794e0.yml
openapi_spec_hash: f1c1d935bb1ab8adf977ca106da721ef
config_hash: 131e5271eed10cf11ebc421d5a0c5f8a
