configured_endpoints: 135
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-eb0ad669503db7e032c39917bac9d4c9d38ccd8ac4d8486963aa6c8b962b8b22.yml
openapi_spec_hash: 5d6becbe5dc1cac7398fd8fbca0a4262
config_hash: c4e43bac321badafc3ba52b6c6c4e646
