configured_endpoints: 107
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/frostedinc%2Fwhopsdk-9bf6f0812f7cf31ce3ed1d9dd74efae84d8c0ee8c8af5042e8472951da9cdad9.yml
openapi_spec_hash: 605d7617f0818ad3e8630d552ee32aa6
config_hash: ce8beecfb0ae26d38cec8c3b63d2a5d6
