// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {
 *         user_ids: ["user_xxxxxxxxxxxxxx"]
 *     }
 */
export interface ListMembersRequest {
    /** The account to list members for (`biz_` tag). Defaults to the account the credential acts as. */
    account_id?: string;
    /** Filter by what the member can reach on the account. */
    access_level?: Whop.ListMembersRequestAccessLevel;
    /** Filter by whether the member is still part of the account. */
    status?: Whop.ListMembersRequestStatus;
    /** Only return members whose users match these `user_` identifiers. */
    user_ids?: string | string[];
    /** Search members by name or username. An exact email address also matches when the credential holds the member:email:read scope. */
    query?: string;
    /** Only members who joined after this ISO 8601 timestamp. */
    created_after?: string;
    /** Only members who joined before this ISO 8601 timestamp. */
    created_before?: string;
    /** Sort field. */
    order?: Whop.ListMembersRequestOrder;
    /** Sort direction. */
    direction?: Whop.ListMembersRequestDirection;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
    /** Number of results to return from the end of the range. */
    last?: number;
    /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
    before?: string;
}
