// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lesson_id: "lesson_id"
 *     }
 */
export interface MarkAsCompletedCourseLessonsRequest {
    /** The unique identifier of the lesson to mark as completed (e.g., "les_XXXXX"). */
    lesson_id: string;
}
