// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "crsli_xxxxxxxxxxxx"
 *     }
 */
export interface RetrieveCourseLessonInteractionsRequest {
    /** The unique identifier of the lesson interaction to retrieve. */
    id: string;
}
