// This file was auto-generated by Fern from our API Definition.

export interface UpdateMethodsResponse {
    /** Masked identifier for the destination. */
    account_reference: string | null;
    /** Lifecycle trust state: `checking` (verification still running), `verified` (bank confirmed ownership or a payout already completed to it), `no_data` (verification unavailable or bank returned no ownership data), `warning` (bank could not confirm the destination's owner), `broken` (payouts failed with a permanent account error), `null` (never checked). */
    bank_verification_state: UpdateMethodsResponse.BankVerificationState | null;
    created_at: string;
    destination_currency: string;
    /** `null` after an update. List payout methods to retrieve arrival estimates. */
    estimated_arrival: Record<string, unknown> | null;
    /** `null` after an update. List payout methods to retrieve the configured fee terms. */
    fee_structure: Record<string, unknown> | null;
    /** Payout method ID, prefixed `potk_`. */
    id: string;
    institution_name: string | null;
    /** Whether this method is a copy of one saved on another of the payer's accounts. */
    is_clone: boolean;
    is_default: boolean;
    /** When the most recent completed payout was delivered to this method, as an ISO 8601 timestamp. `null` when nothing has been paid out to it yet. */
    last_paid_out_at: string | null;
    /** Whether the payer added this method by signing in to their bank rather than typing account details. */
    linked_via_plaid: boolean;
    /** Whether the bank sign-in behind this method has expired and must be redone before it counts as linked. */
    needs_plaid_reconnect: boolean;
    /** User-defined label for the payout method. */
    nickname: string | null;
    object: UpdateMethodsResponse.Object_;
    payer_name: string | null;
    /** Always `null` after an update. */
    quote: Record<string, unknown> | null;
    /** `created` — saved, no payout has completed through it yet. `active` — a payout through it completed. `broken` — a payout through it failed with an error attributable to the method, and it no longer accepts payouts; a later successful payout returns it to `active`. */
    status: UpdateMethodsResponse.Status;
    /** Machine-readable code for why the method is `broken` — the newest failure recorded through it, whether a payout error or a pre-payout rejection. `null` unless the method is broken, or when it was disabled without a recorded failure. */
    status_reason: string | null;
    supported_payout_method: UpdateMethodsResponse.SupportedPayoutMethod | null;
    /** Why this method is unavailable: `destination_retired` means the payout provider stopped offering the destination. Whop may automatically remap an eligible method that was not linked through Plaid to a compatible replacement; otherwise, the account owner must re-add it. `null` means no unavailability reason is known. */
    unavailable_reason: UpdateMethodsResponse.UnavailableReason | null;
}

export namespace UpdateMethodsResponse {
    /** Lifecycle trust state: `checking` (verification still running), `verified` (bank confirmed ownership or a payout already completed to it), `no_data` (verification unavailable or bank returned no ownership data), `warning` (bank could not confirm the destination's owner), `broken` (payouts failed with a permanent account error), `null` (never checked). */
    export const BankVerificationState = {
        Checking: "checking",
        Verified: "verified",
        NoData: "no_data",
        Warning: "warning",
        Broken: "broken",
    } as const;
    export type BankVerificationState = (typeof BankVerificationState)[keyof typeof BankVerificationState];
    export const Object_ = {
        PayoutMethod: "payout_method",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
    /** `created` — saved, no payout has completed through it yet. `active` — a payout through it completed. `broken` — a payout through it failed with an error attributable to the method, and it no longer accepts payouts; a later successful payout returns it to `active`. */
    export const Status = {
        Created: "created",
        Active: "active",
        Broken: "broken",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface SupportedPayoutMethod {
        /** ISO 3166-1 alpha-3 country the destination pays out to. */
        country_code: string | null;
        /** How funds are delivered. */
        delivery_type: SupportedPayoutMethod.DeliveryType;
        icon_url: string | null;
        name: string | null;
        supports_instant_delivery: boolean;
        /** Whether the payer can link this method by signing in to their bank instead of typing account details. */
        supports_plaid: boolean;
        supports_standard_delivery: boolean;
    }

    export namespace SupportedPayoutMethod {
        /** How funds are delivered. */
        export const DeliveryType = {
            CashPickup: "cash_pickup",
            BankDeposit: "bank_deposit",
            HomeDelivery: "home_delivery",
            MobileWallet: "mobile_wallet",
            Card: "card",
            Check: "check",
            Bill: "bill",
            Cryptocurrency: "cryptocurrency",
            Unknown: "unknown",
        } as const;
        export type DeliveryType = (typeof DeliveryType)[keyof typeof DeliveryType];
    }

    /** Why this method is unavailable: `destination_retired` means the payout provider stopped offering the destination. Whop may automatically remap an eligible method that was not linked through Plaid to a compatible replacement; otherwise, the account owner must re-add it. `null` means no unavailability reason is known. */
    export const UnavailableReason = {
        DestinationRetired: "destination_retired",
    } as const;
    export type UnavailableReason = (typeof UnavailableReason)[keyof typeof UnavailableReason];
}
