// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../index.js";

/**
 * The connection type for Affiliate.
 */
export interface ListAffiliatesResponse {
    /** A list of nodes. */
    data: Whop.AffiliateListItem[];
    /** Information to aid in pagination. */
    page_info: Whop.PageInfo;
}
