// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Whop from "../../../index.js";

export declare namespace CardsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Cards represent Whop-issued virtual payment cards that spend from an account or user balance. Cards can be assigned to cardholders and configured with spending limits for controlled spending.
 *
 * Use the Cards API to issue cards, list cards for an account or user, and retrieve active card details such as the card number and CVC.
 */
export class CardsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CardsClient.Options>;

    constructor(options: CardsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists the Whop cards of an account or user, including ones still being set up. Team members only see the cards assigned to them.
     *
     * @param {Whop.ListCardsRequest} request
     * @param {CardsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.cards.list()
     */
    public list(
        request: Whop.ListCardsRequest = {},
        requestOptions?: CardsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.ListCardsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Whop.ListCardsRequest = {},
        requestOptions?: CardsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.ListCardsResponse>> {
        const { account_id: accountId, user_id: userId } = request;
        const _queryParams: Record<string, unknown> = {
            account_id: accountId,
            user_id: userId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-25-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                "cards",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.ListCardsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/cards");
    }

    /**
     * Issue a virtual card, or apply for card issuing.
     *
     * @param {Whop.CreateCardsRequest} request
     * @param {CardsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.ConflictError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.cards.create()
     */
    public create(
        request: Whop.CreateCardsRequest = {},
        requestOptions?: CardsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.CreateCardsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Whop.CreateCardsRequest = {},
        requestOptions?: CardsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.CreateCardsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-25-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                "cards",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.CreateCardsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Whop.ConflictError(_response.error.body as Whop.V1ErrorResponse, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/cards");
    }

    /**
     * Retrieve a single card.
     *
     * @param {Whop.RetrieveCardsRequest} request
     * @param {CardsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.cards.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Whop.RetrieveCardsRequest,
        requestOptions?: CardsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.RetrieveCardsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Whop.RetrieveCardsRequest,
        requestOptions?: CardsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.RetrieveCardsResponse>> {
        const { id, account_id: accountId, user_id: userId } = request;
        const _queryParams: Record<string, unknown> = {
            account_id: accountId,
            user_id: userId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-25-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `cards/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.RetrieveCardsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/cards/{id}");
    }

    /**
     * Update, freeze, or cancel a card. Updating the card's name, billing address, or limits requires both `payout:account:update` and `company:balance:read`; a card's assigned holder may update their own card's pin and frozen state with any user token.
     *
     * @param {Whop.UpdateCardsRequest} request
     * @param {CardsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.ConflictError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.cards.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Whop.UpdateCardsRequest,
        requestOptions?: CardsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.UpdateCardsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Whop.UpdateCardsRequest,
        requestOptions?: CardsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.UpdateCardsResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-08-25-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `cards/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.UpdateCardsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Whop.ConflictError(_response.error.body as Whop.V1ErrorResponse, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/cards/{id}");
    }
}
