// This file was auto-generated by Fern from our API Definition.

export const ListOauthGrantsRequestOrder = {
    CreatedAt: "created_at",
} as const;
export type ListOauthGrantsRequestOrder =
    (typeof ListOauthGrantsRequestOrder)[keyof typeof ListOauthGrantsRequestOrder];
