// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Whop from "../../../index.js";

export declare namespace RefundsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * A Refund is one reversal of a payment, full or partial. Refunds are issued with `POST /payments/{id}/refund`; this resource is the record of each one — how much moved, through which provider, and where it stands (`pending`, `succeeded`, `failed`).
 *
 * List a payment's refunds with `?payment_id=`, or every refund an account issued with `?account_id=`. `amount` is stated in the payment's settlement currency so it nets against the payment's `total`; `original_amount` is what the processor moved.
 */
export class RefundsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RefundsClient.Options>;

    constructor(options: RefundsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists refunds, newest first. Without filters this is every refund the caller can read; narrow it to one payment with `payment_id`, one account with `account_id`, or one buyer with `user_id`.
     *
     * @param {Whop.ListRefundsRequest} request
     * @param {RefundsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.refunds.list()
     */
    public async list(
        request: Whop.ListRefundsRequest = {},
        requestOptions?: RefundsClient.RequestOptions,
    ): Promise<core.Page<Whop.Refund, Whop.ListRefundsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Whop.ListRefundsRequest): Promise<core.WithRawResponse<Whop.ListRefundsResponse>> => {
                const {
                    account_id: accountId,
                    payment_id: paymentId,
                    user_id: userId,
                    created_before: createdBefore,
                    created_after: createdAfter,
                    order,
                    direction,
                    first,
                    after,
                    last,
                    before,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    account_id: accountId,
                    payment_id: paymentId,
                    user_id: userId,
                    created_before: createdBefore != null ? createdBefore : undefined,
                    created_after: createdAfter != null ? createdAfter : undefined,
                    order: order != null ? order : undefined,
                    direction: direction != null ? direction : undefined,
                    first,
                    after,
                    last,
                    before,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        "Api-Version-Date":
                            requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-1",
                        "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.WhopEnvironment.Default,
                        "refunds",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Whop.ListRefundsResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                        case 401:
                            throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                        case 404:
                            throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                        default:
                            throw new errors.WhopError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/refunds");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Whop.Refund, Whop.ListRefundsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.page_info.end_cursor != null &&
                !(typeof response?.page_info.end_cursor === "string" && response?.page_info.end_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "after", response?.page_info.end_cursor));
            },
        });
    }

    /**
     * Returns one refund.
     *
     * @param {Whop.RetrieveRefundsRequest} request
     * @param {RefundsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.refunds.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Whop.RetrieveRefundsRequest,
        requestOptions?: RefundsClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.Refund> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Whop.RetrieveRefundsRequest,
        requestOptions?: RefundsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.Refund>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-1",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `refunds/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.Refund, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/refunds/{id}");
    }
}
