// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {
 *         first: 42,
 *         last: 42,
 *         account_id: "biz_xxxxxxxxxxxxxx"
 *     }
 */
export interface ListAffiliatesRequest {
    /** Returns the elements in the list that come after the specified cursor. */
    after?: string;
    /** Returns the elements in the list that come before the specified cursor. */
    before?: string;
    /** Returns the first _n_ elements from the list. */
    first?: number;
    /** Returns the last _n_ elements from the list. */
    last?: number;
    direction?: Whop.Direction;
    order?: Whop.AffiliatesSortableColumns;
    /** Search affiliates by username. */
    query?: string;
    status?: Whop.Status;
    /** The unique identifier of the company to list affiliates for. */
    account_id: string;
}
