// This file was auto-generated by Fern from our API Definition.

export const ListAdPixelsRequestOrder = {
    CreatedAt: "created_at",
} as const;
export type ListAdPixelsRequestOrder = (typeof ListAdPixelsRequestOrder)[keyof typeof ListAdPixelsRequestOrder];
