// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListLogsRequest {
    /** Member ID (`mber_` tag). */
    id: string;
    /** Number of log entries to return from the start of the window. */
    first?: number;
    /** Cursor to paginate forwards from. */
    after?: string;
    /** Number of log entries to return from the end of the window. */
    last?: number;
    /** Cursor to paginate backwards from. */
    before?: string;
}
