// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../index.js";

export type CreateTransfersRequestBody =
    /**
     * Moves credit between two Whop balances and returns a `transfer`. A transfer from a stablecoin-rails account settles on-chain when covered, and still returns a `transfer`. */
    | Whop.CreateTransfersRequestBody.Balance
    /**
     * Funds a shareable link anyone with the URL can redeem and returns a `claim_link`. */
    | Whop.CreateTransfersRequestBody.ClaimLink;

export namespace CreateTransfersRequestBody {
    export interface Balance {
        type: "balance";
        /** The amount to move, in the transfer currency. For example 25.00. */
        amount: number;
        /** Currency, such as `usd`. */
        currency: string;
        /** The recipient. A user ID (user_xxx), account ID (biz_xxx), or ledger account ID (ldgr_xxx). */
        destination_id: string;
        /** The feed the transfer was initiated from. Given with `feed_type`, the payment receipt posts into that feed instead of a direct message. */
        feed_id?: (string | null) | undefined;
        /** The type of the feed named by `feed_id`. */
        feed_type?: (CreateTransfersRequestBodyBalance.FeedType | null) | undefined;
        /** A unique key that makes retries safe. Retrying with the same key returns the original transfer instead of moving money twice. */
        idempotence_key?: (string | null) | undefined;
        /** Custom key-value pairs attached to the transfer. Max 50 keys, 100 chars per key, 500 chars per string value. */
        metadata?: (Record<string, unknown> | null) | undefined;
        /** A short note describing the transfer. */
        notes?: (string | null) | undefined;
        /** The account sending the funds. A user ID (user_xxx), account ID (biz_xxx), or ledger account ID (ldgr_xxx). */
        origin_id: string;
    }

    export namespace CreateTransfersRequestBodyBalance {
        /** The type of the feed named by `feed_id`. */
        export const FeedType = {
            DmsFeed: "dms_feed",
            ChatFeed: "chat_feed",
            ForumFeed: "forum_feed",
            LivestreamFeed: "livestream_feed",
            UniversalPost: "universal_post",
            User: "user",
        } as const;
        export type FeedType = (typeof FeedType)[keyof typeof FeedType];
    }

    export interface ClaimLink {
        type: "claim_link";
        /** The amount to move, in the transfer currency. For example 25.00. */
        amount: number;
        /** Link expiry as an ISO 8601 timestamp. Defaults to 24 hours from creation. */
        expires_at?: (string | null) | undefined;
        /** The account sending the funds. A user ID (user_xxx), account ID (biz_xxx), or ledger account ID (ldgr_xxx). */
        origin_id: string;
        /** How many different users can claim the link. Defaults to 1. */
        redeemable_count?: number | undefined;
    }
}
