// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateAdConversionValueRulesRequest {
    /** Conversion value rule ID. */
    id: string;
    adjustment_type?: UpdateAdConversionValueRulesRequest.AdjustmentType;
    /** Events adjusted on every selected target. Every platform must support every selected event. */
    events?: UpdateAdConversionValueRulesRequest.Events.Item[];
    fixed_value?: UpdateAdConversionValueRulesRequest.FixedValue | null;
    metadata?: Record<string, string>;
    /** Signed percent change from negative 100 to 10000. The sent value cannot go below zero. */
    percentage_change?: number | null;
    /** Exact IDs of active rules whose overlapping selections will be replaced. Other selections keep their values; remaining selections may split into separate rules. Broader rules remain as fallbacks for other items. Stale or incomplete conflict selections fail. */
    replace_rule_ids?: string[];
    /** Targets sharing one scope. Every selected event applies to every target. At most 500 target and event combinations. */
    targets?: UpdateAdConversionValueRulesRequest.Targets.Item[];
}

export namespace UpdateAdConversionValueRulesRequest {
    export const AdjustmentType = {
        Fixed: "fixed",
        Percentage: "percentage",
    } as const;
    export type AdjustmentType = (typeof AdjustmentType)[keyof typeof AdjustmentType];
    export type Events = Events.Item[];

    export namespace Events {
        export interface Item {
            /** Exact custom event name. Required for custom events; null for standard events. */
            custom_name?: (string | null) | undefined;
            event_name: Item.EventName;
        }

        export namespace Item {
            export const EventName = {
                Purchase: "purchase",
                Subscribe: "subscribe",
                StartTrial: "start_trial",
                Lead: "lead",
                CompleteRegistration: "complete_registration",
                SubmitApplication: "submit_application",
                Schedule: "schedule",
                Contact: "contact",
                ViewContent: "view_content",
                AddToCart: "add_to_cart",
                Custom: "custom",
            } as const;
            export type EventName = (typeof EventName)[keyof typeof EventName];
        }
    }

    export interface FixedValue {
        /** Decimal amount with at most 2 decimal places. Fixed values must be greater than 0 and at most 99999999.99. */
        amount: string;
        currency: string;
    }

    export type Targets = Targets.Item[];

    export namespace Targets {
        export interface Item {
            platform: Item.Platform;
            /** Campaign, ad group, or ad ID. Null for a business target. */
            resource_id?: (string | null) | undefined;
            scope: Item.Scope;
        }

        export namespace Item {
            export const Platform = {
                Tiktok: "tiktok",
                Meta: "meta",
                Google: "google",
            } as const;
            export type Platform = (typeof Platform)[keyof typeof Platform];
            export const Scope = {
                Business: "business",
                Campaign: "campaign",
                AdGroup: "ad_group",
                Ad: "ad",
            } as const;
            export type Scope = (typeof Scope)[keyof typeof Scope];
        }
    }
}
