// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RetrieveAccountsRequest {
    /** Account ID, prefixed `biz_`, or its public route. */
    id: string;
}
