// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../../../../src/api/index";
import { WhopClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("TopicsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    created_at: "2026-01-01T12:00:00.000Z",
                    id: "unpf_xxxxxxxxxxxxxx",
                    level: "all",
                    object: "notification_preference",
                    scope: {
                        account_id: "biz_xxxxxxxxxxxxxx",
                        channel: null,
                        experience_id: "exp_xxxxxxxxxxxxxx",
                        team_account_id: "biz_xxxxxxxxxxxxxx",
                        topic_id: "topic_xxxxxxxxxxxxxx",
                    },
                    updated_at: "2026-01-01T12:00:00.000Z",
                },
            ],
            page_info: {
                end_cursor: "end_cursor",
                has_next_page: false,
                has_previous_page: false,
                start_cursor: "WyJjdXJzb3IiLDFd",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/users/me/preferences/notifications/topics")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.users.preferences.notifications.topics.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/users/me/preferences/notifications/topics")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.preferences.notifications.topics.list();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });
});
