// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListCashbackRulesRequest {
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
    /** Number of results to return from the end of the range. */
    last?: number;
    /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
    before?: string;
    /** Field to sort by. Defaults to created_at. */
    order?: Whop.ListCashbackRulesRequestOrder;
    /** Sort direction. Defaults to desc. */
    direction?: Whop.ListCashbackRulesRequestDirection;
}
