// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreatePlansRequest {
    account_id?: string;
    adaptive_pricing_enabled?: boolean | null;
    attributes?: Record<string, unknown> | null;
    billing_period?: number | null;
    checkout_styling?: Record<string, unknown> | null;
    currency?: string;
    custom_fields?: CreatePlansRequest.CustomFields.Item[] | null;
    description?: string | null;
    expiration_days?: number | null;
    image?: CreatePlansRequest.Image | null;
    initial_price?: number | null;
    internal_notes?: string | null;
    metadata?: Record<string, unknown> | null;
    override_tax_type?: string;
    payment_method_configuration?: CreatePlansRequest.PaymentMethodConfiguration | null;
    plan_type?: string;
    product_id?: string;
    release_method?: string;
    renewal_price?: number | null;
    sku?: string | null;
    split_pay_required_payments?: number | null;
    stock?: number | null;
    three_ds_level?: CreatePlansRequest.ThreeDsLevel | null;
    title?: string | null;
    trial_period_days?: number | null;
    unlimited_stock?: boolean | null;
    visibility?: string;
}

export namespace CreatePlansRequest {
    export type CustomFields = CustomFields.Item[];

    export namespace CustomFields {
        export interface Item {
            field_type?: Item.FieldType | undefined;
            id?: string | undefined;
            name?: string | undefined;
            order?: number | undefined;
            placeholder?: (string | null) | undefined;
            required?: boolean | undefined;
        }

        export namespace Item {
            export const FieldType = {
                Text: "text",
            } as const;
            export type FieldType = (typeof FieldType)[keyof typeof FieldType];
        }
    }

    export interface Image {
        direct_upload_id?: string | undefined;
        id?: string | undefined;
    }

    export interface PaymentMethodConfiguration {
        disabled?: Whop.PaymentMethodTypes[] | undefined;
        enabled?: Whop.PaymentMethodTypes[] | undefined;
        include_platform_defaults?: boolean | undefined;
    }

    export const ThreeDsLevel = {
        MandateChallenge: "mandate_challenge",
        MandateIfRequired: "mandate_if_required",
        FrictionlessIfRequired: "frictionless_if_required",
    } as const;
    export type ThreeDsLevel = (typeof ThreeDsLevel)[keyof typeof ThreeDsLevel];
}
