// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSupportedMethodsRequest {
    /** The owning account ID (a biz_ identifier). Provide this or user_id. */
    account_id?: string;
    /** The owning user ID (a user_ identifier). Provide this or account_id. */
    user_id?: string;
    /** ISO 3166-1 alpha-2 country code for the bank account or wallet, such as `US`. Defaults to the country of supported_payout_method_id when one is given, otherwise the payout account's country. */
    country?: string;
    /** Optional payout amount in whole currency units, for example `250.00`. When provided, each destination includes per-currency fee and delivery quotes. */
    amount?: number;
    /** Currency code of the amount, for example `usd`. Only meaningful with amount. */
    currency?: string;
    /** Narrows the list to one supported payout method (a podst_ identifier) and includes the required_fields needed to save it as a payout method. */
    supported_payout_method_id?: string;
    /** Currency the supported payout method would deliver payouts in. Only meaningful with supported_payout_method_id; required fields vary by destination currency. */
    destination_currency?: string;
    /** Number of supported payout methods to return from the start of the window. */
    first?: number;
    /** Cursor to fetch the page after (from page_info.end_cursor). */
    after?: string;
    /** Number of supported payout methods to return from the end of the window. */
    last?: number;
    /** Cursor to fetch the page before (from page_info.start_cursor). */
    before?: string;
}
