// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         resource: "ad_campaigns"
 *     }
 */
export interface CreateExportsRequest {
    /** The account to export from, prefixed `biz_`. Defaults to the credential's account. */
    account_id?: string;
    /** Column keys to include. Empty means all columns for the resource. */
    columns?: string[];
    /** Resource-specific filters. For native REST resources (`payouts`, `transfers`, `products`) these are the resource's own list query params; for dashboard tables they mirror the dashboard table filters. */
    filters?: Record<string, unknown>;
    /** The resource to export, e.g. `payouts`, `receipts`, or `members`. */
    resource: CreateExportsRequest.Resource;
    /** IANA timezone for date columns, e.g. `America/New_York`. Defaults to `UTC`. */
    timezone?: string;
}

export namespace CreateExportsRequest {
    /** The resource to export, e.g. `payouts`, `receipts`, or `members`. */
    export const Resource = {
        AdCampaigns: "ad_campaigns",
        AdGroups: "ad_groups",
        Ads: "ads",
        Apps: "apps",
        Audiences: "audiences",
        Bounties: "bounties",
        BountySubmissions: "bounty_submissions",
        CardTransactions: "card_transactions",
        CheckoutConfigurations: "checkout_configurations",
        Disputes: "disputes",
        Events: "events",
        FinancialActivity: "financial-activity",
        PayoutMethods: "payout_methods",
        Payouts: "payouts",
        People: "people",
        Plans: "plans",
        Products: "products",
        ResolutionCenterCases: "resolution_center_cases",
        Shipments: "shipments",
        SocialAccounts: "social_accounts",
        TeamMembers: "team_members",
        Transfers: "transfers",
        Webhooks: "webhooks",
        Members: "members",
        Receipts: "receipts",
        UnclaimedMemberships: "unclaimed_memberships",
        Memberships: "memberships",
        TrackingLinks: "tracking_links",
        PromoCodes: "promo_codes",
        Resolutions: "resolutions",
        Entries: "entries",
        Leads: "leads",
        ContentRewardsSubmissions: "content_rewards_submissions",
        Invoices: "invoices",
        CancelationReasons: "cancelation_reasons",
        ChildCompanies: "child_companies",
    } as const;
    export type Resource = (typeof Resource)[keyof typeof Resource];
}
