// This file was auto-generated by Fern from our API Definition.

/** The ways a relation of AccessPasses can be ordered */
export const AccessPassOrder = {
    ActiveMembershipsCount: "active_memberships_count",
    CreatedAt: "created_at",
    UsdGmv: "usd_gmv",
    UsdGmv30Days: "usd_gmv_30_days",
} as const;
export type AccessPassOrder = (typeof AccessPassOrder)[keyof typeof AccessPassOrder];
