// This file was auto-generated by Fern from our API Definition.

/** The different types an product can be. Only use 'regular'. The rest are for internal use */
export const AccessPassTypes = {
    Regular: "regular",
    App: "app",
    ExperienceUpsell: "experience_upsell",
    ApiOnly: "api_only",
} as const;
export type AccessPassTypes = (typeof AccessPassTypes)[keyof typeof AccessPassTypes];
