// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface AccountPartnerReward {
    /** Reward definition ID, prefixed `prwd_`. Progress and status apply to the containing account. */
    id: string;
    /** Qualifying USD volume required to earn this reward. */
    qualification_amount: Whop.Money;
    /** Qualifying USD volume for the reward’s activity accumulated by this account since attribution, calculated using the fulfillment rules. */
    qualification_progress: Whop.Money;
    /** Activity that qualifies this account for the reward. */
    qualification_type: AccountPartnerReward.QualificationType;
    /** USD balance credit for this reward. Uses the saved grant amount once fulfillment has started. */
    reward_amount: Whop.Money;
    /** This account's reward state. Credited requires a posted ledger entry; processing includes a met requirement awaiting fulfillment. Reversing and reversed reflect a subsequent reward reversal. */
    status: AccountPartnerReward.Status;
}

export namespace AccountPartnerReward {
    /** Activity that qualifies this account for the reward. */
    export const QualificationType = {
        Sales: "sales",
        AdSpend: "ad_spend",
    } as const;
    export type QualificationType = (typeof QualificationType)[keyof typeof QualificationType];
    /** This account's reward state. Credited requires a posted ledger entry; processing includes a met requirement awaiting fulfillment. Reversing and reversed reflect a subsequent reward reversal. */
    export const Status = {
        InProgress: "in_progress",
        Processing: "processing",
        Credited: "credited",
        Reversing: "reversing",
        Reversed: "reversed",
        Unavailable: "unavailable",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
