// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface AccountPaymentControls {
    /** Automatic refund settings for pre-chargeback dispute alerts. */
    dispute_alert_auto_refund: Whop.AccountDisputeAlertAutoRefundControl;
    /** Fee charged for each dispute alert in USD. `null` when unavailable. */
    dispute_alert_fee_usd: number | null;
    /** Whether 3-D Secure is forced on every card payment at checkout. The account cannot bypass it while set. */
    enforce_3ds: boolean;
    /** Whether payment health controls explicitly disable financing. This is independent of financing approval in `capabilities.accept_bnpl_payments`. */
    financing_disabled: boolean;
    /** Additional processing fee percentage for high-risk processing. */
    high_risk_processing_fee_percentage: number;
    /** Percentage fee charged when pending, not-yet-settled balance is advanced to fund the account's cards balance, where `2` means 2%. `0` when the account is exempt. */
    pending_auto_topup_fee_percentage: number;
    /** Additional days payments remain pending before becoming available. */
    pending_balance_delay_days: number;
    /** Reserve currently applied to incoming payment volume. */
    reserve: Whop.AccountReserveControl;
    /** Automatic refund settings for resolution center cases. */
    resolution_center_auto_refund: Whop.AccountResolutionCenterAutoRefundControl;
    restricted_payment_methods: AccountPaymentControls.RestrictedPaymentMethods.Item[];
    /** Why pending funds without a settlement date aren't moving yet, when it's something the merchant can act on. `null` when there's no reason to show (still clearing, or the account is held for a reason that isn't merchant-actionable). */
    undated_pending_reason: AccountPaymentControls.UndatedPendingReason | null;
    /** How the account's balance automatically withdraws. */
    withdrawal_schedule: Whop.AccountWithdrawalScheduleControl;
}

export namespace AccountPaymentControls {
    export type RestrictedPaymentMethods = RestrictedPaymentMethods.Item[];

    export namespace RestrictedPaymentMethods {
        /** Card brands blocked at checkout for this account. Empty when none are blocked. The account cannot re-enable them itself. */
        export const Item = {
            CardVisa: "card_visa",
            CardMastercard: "card_mastercard",
            CardAmericanExpress: "card_american_express",
            CardDiscoverGlobalNetwork: "card_discover_global_network",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Why pending funds without a settlement date aren't moving yet, when it's something the merchant can act on. `null` when there's no reason to show (still clearing, or the account is held for a reason that isn't merchant-actionable). */
    export const UndatedPendingReason = {
        KycIncomplete: "kyc_incomplete",
        PendingInformationRequest: "pending_information_request",
    } as const;
    export type UndatedPendingReason = (typeof UndatedPendingReason)[keyof typeof UndatedPendingReason];
}
