// This file was auto-generated by Fern from our API Definition.

export interface AccountFinancing {
    /** The ID of the account's most recent financing application, starting with inrq_. Retrieve it for requirements and review feedback. */
    application_id: string;
    /** The most recent financing application's review state: `requires_collection` (waiting on the merchant, including after a request for more information), `awaiting_review`, `approved`, `denied`, or `completed`. Whether financing payment methods are enabled is `capabilities.accept_bnpl_payments`. */
    status: AccountFinancing.Status;
}

export namespace AccountFinancing {
    /** The most recent financing application's review state: `requires_collection` (waiting on the merchant, including after a request for more information), `awaiting_review`, `approved`, `denied`, or `completed`. Whether financing payment methods are enabled is `capabilities.accept_bnpl_payments`. */
    export const Status = {
        RequiresCollection: "requires_collection",
        AwaitingReview: "awaiting_review",
        Completed: "completed",
        Approved: "approved",
        Denied: "denied",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
