// This file was auto-generated by Fern from our API Definition.

export interface AdGroupTargetingCategory {
    /** The ad platform's ID for the category in its targeting taxonomy. */
    id: string;
    /** Category name, such as `Movies`. */
    name?: string | undefined;
}
