// This file was auto-generated by Fern from our API Definition.

export interface AdLeadFormCompletion {
    /** Text of the follow-up button. */
    button_text: string | null;
    /** Body text under the headline. */
    description: string | null;
    /** Headline of the completion screen. */
    headline: string | null;
    /** Website the follow-up button opens. `null` when the screen has no button. */
    url: string | null;
}
