// This file was auto-generated by Fern from our API Definition.

export interface AdText {
    /** ISO 639 code of the language this text is in, such as `es`. On an ad with translations, the ad's own copy carries `translations.source_language`. It's `null` on an ad without translations. */
    language: string | null;
    /** The text shown to viewers. */
    text: string;
}
