// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

/**
 * An AI-powered chat conversation belonging to a user, with optional scheduled automation.
 */
export interface AiChatListItem {
    /** The total number of tokens consumed across all messages in this conversation. */
    blended_token_usage: string;
    /** The datetime the ai chat was created. */
    created_at: string;
    /** The unique identifier for the ai chat. */
    id: string;
    /** The timestamp of the most recent message in this conversation. Null if no messages have been sent yet. */
    last_message_at: string | null;
    /** The total number of messages exchanged in this conversation. */
    message_count: number;
    /** The notification preference for this AI chat. `all` delivers AI chat notifications and badges, while `none` mutes them. */
    notification_preference: Whop.AiChatNotificationPreferences;
    /** A short descriptive title for this AI chat conversation. Null if no title has been set. */
    title: string | null;
    /** The datetime the ai chat was last updated. */
    updated_at: string;
    /** The user who owns this AI chat conversation. */
    user: AiChatListItem.User;
}

export namespace AiChatListItem {
    /**
     * The user who owns this AI chat conversation.
     */
    export interface User {
        /** The unique identifier for the user. */
        id: string;
    }
}
