// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyGrantAction {
    /** The permission action's identifier, for example `company:basic:read`. */
    action: string;
    /** Whether the key holds the action on the grant's resource. */
    granted: boolean;
}
