// This file was auto-generated by Fern from our API Definition.

/** The different API versions */
export const ApiVersion = {
    V1: "v1",
    V2: "v2",
    V5: "v5",
} as const;
export type ApiVersion = (typeof ApiVersion)[keyof typeof ApiVersion];
