// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface App {
    /** The account that owns the app. */
    account: Whop.AccountParent;
    /** Legacy app API key used to authenticate requests on the app's behalf. `null` when no key exists or the caller lacks the `developer:manage_api_key` permission. */
    api_key: Whop.AppApiKey | null;
    /** Detailed description shown on the app store's in-depth app page, or `null` when none has been set. */
    app_store_description: string | null;
    /** The type of end-user the app is built for. */
    app_type: App.AppType;
    /** Banner image from the app's product listing, or `null` when none is uploaded. */
    banner_image: Whop.AppBannerImage | null;
    /** The production base URL where the app is hosted. `null` if no base URL is configured, if the caller lacks the `developer:basic:read` permission on the app's account, or on list responses, which never expose it. */
    base_url: string | null;
    /** Website businesses created from this app as a template. */
    businesses_created_count: number;
    businesses_created_logo_urls: string[];
    /** The user who owns the publishing account. */
    creator: Whop.AppCreator;
    /** URL path for the account dashboard view, or `null` when not configured. */
    dashboard_path: string | null;
    /** The app's default API key. `null` when the app has no default key or the caller lacks the `developer:manage_api_key` permission; `secret_key` is additionally `null` unless the caller could have created the key themselves. */
    default_api_key: Whop.AppDefaultApiKey | null;
    /** What the app has left to publish, and how a publish in flight is going — `status` is only ever `unpublished`, `publishing`, or `failed` here. `null` means there is nothing to report: the app is fully published, there is no working copy to publish from, or the caller cannot deploy this app. Tell those apart from the app's own `production_web_build`. */
    deployment: Whop.AppDeployment | null;
    /** Short description shown in listings and search results, or `null` if none has been set. */
    description: string | null;
    /** URL path for the discover view, or `null` when not configured. */
    discover_path: string | null;
    /** Subdomain identifier for the app's proxied URL, forming https://{domain_id}.apps.whop.com. */
    domain_id: string;
    /** URL path for the member-facing hub view, or `null` when not configured. */
    experience_path: string | null;
    /** Full URL where the app's hosted web build is served, or `null` if no route is claimed. */
    hosted_url: string | null;
    /** The app's icon. Falls back to the default app icon when none is uploaded. */
    icon: Whop.AppIcon;
    /** App ID, prefixed `app_`. */
    id: string;
    /** Approval status of the app's product listing on the Whop app store, or `null` when the app has no associated product. */
    marketplace_status: App.MarketplaceStatus | null;
    /** Display name shown on the app store and in experience navigation. */
    name: string;
    /** How the app authenticates at the OAuth token endpoint. */
    oauth_client_type: App.OauthClientType;
    /** URL path to the app's OpenAPI spec file, or `null` when not configured. */
    openapi_path: string | null;
    /** Full origin URL of the app's proxied domain, for example https://ab1c2d3e4f.apps.whop.com. */
    origin: string | null;
    /** ID of the app's product listing on the Whop app store, or `null` when the app has no associated product. */
    product_id: string | null;
    /** The approved build currently served on Android, or `null` when none is deployed. */
    production_android_build: Whop.AppProductionBuild | null;
    /** The approved build currently served on iOS, or `null` when none is deployed. */
    production_ios_build: Whop.AppProductionBuild | null;
    /** The approved build currently served on web, or `null` when none is deployed. */
    production_web_build: Whop.AppProductionBuild | null;
    redirect_uris: string[];
    requested_permissions: Whop.AppRequestedPermission[];
    required_scopes: App.RequiredScopes.Item[];
    /** Claimed subdomain route where hosted web builds are served (`myapp` for myapp.whop.app), or `null` if no route is claimed. */
    route: string | null;
    /** The app's production secrets as an object of string values, injected into the hosted server runtime. `null` when the caller lacks the `developer:update_app` permission. */
    secrets: Record<string, unknown> | null;
    /** URL path to the app's skills directory, or `null` when not configured. */
    skills_path: string | null;
    /** Visibility on the Whop app store: `live` is publicly discoverable, `unlisted` is accessible only via direct link, `hidden` is not visible anywhere. */
    status: App.Status;
    /** Whether the app has been verified by Whop and is eligible for the featured apps section. */
    verified: boolean;
}

export namespace App {
    /** The type of end-user the app is built for. */
    export const AppType = {
        B2BApp: "b2b_app",
        B2CApp: "b2c_app",
        CompanyApp: "company_app",
        Component: "component",
        Website: "website",
    } as const;
    export type AppType = (typeof AppType)[keyof typeof AppType];
    /** Approval status of the app's product listing on the Whop app store, or `null` when the app has no associated product. */
    export const MarketplaceStatus = {
        NotAvailable: "not_available",
        PendingReview: "pending_review",
        LiveMarketplace: "live_marketplace",
    } as const;
    export type MarketplaceStatus = (typeof MarketplaceStatus)[keyof typeof MarketplaceStatus];
    /** How the app authenticates at the OAuth token endpoint. */
    export const OauthClientType = {
        Public: "public",
        Confidential: "confidential",
    } as const;
    export type OauthClientType = (typeof OauthClientType)[keyof typeof OauthClientType];
    export type RequiredScopes = RequiredScopes.Item[];

    export namespace RequiredScopes {
        /** Scopes the app asks a user to grant when they authorize it, shown on the consent screen. */
        export const Item = {
            ReadUser: "read_user",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Visibility on the Whop app store: `live` is publicly discoverable, `unlisted` is accessible only via direct link, `hidden` is not visible anywhere. */
    export const Status = {
        Live: "live",
        Unlisted: "unlisted",
        Hidden: "hidden",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
