// This file was auto-generated by Fern from our API Definition.

export interface AppProductionBuild {
    /** Client-generated checksum of the build file, used to verify file integrity. */
    checksum: string | null;
    /** URL to download the uploaded build artifact. */
    file_url: string | null;
    /** App build ID, prefixed `abld_`. */
    id: string;
    /** URL to download the compressed source code archive that produced this build, or `null` when the build was uploaded without a source archive. */
    source_url: string | null;
    /** The build's review status. */
    status: AppProductionBuild.Status;
}

export namespace AppProductionBuild {
    /** The build's review status. */
    export const Status = {
        Draft: "draft",
        Pending: "pending",
        Approved: "approved",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
