// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface AudienceEngagement {
    /** Exclude anyone matching any exclusion rule. Supply 0–10 rules. Video audiences do not support exclusions; use a separate audience in ad-group exclusions. */
    exclude: Whop.AudienceEngagementRule[];
    /** Match any inclusion rule. Supply 1–10 rules. Video rules must share a retention window and cannot be combined with other sources. */
    include: Whop.AudienceEngagementRule[];
    /** Ad platform that maintains membership. */
    platform: AudienceEngagement.Platform;
}

export namespace AudienceEngagement {
    /** Ad platform that maintains membership. */
    export const Platform = {
        Meta: "meta",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
}
