// This file was auto-generated by Fern from our API Definition.

/** What the poster is trying to accomplish with a workforce bounty. Used for product taxonomy and analytics, separate from the bounty's implementation type. */
export const BusinessGoalTypes = {
    Clipping: "clipping",
    PostEngagement: "post_engagement",
    OwnedAccountGrowth: "owned_account_growth",
    UgcContent: "ugc_content",
    LocalActivation: "local_activation",
    DataCapture: "data_capture",
    Other: "other",
} as const;
export type BusinessGoalTypes = (typeof BusinessGoalTypes)[keyof typeof BusinessGoalTypes];
