// This file was auto-generated by Fern from our API Definition.

export interface CheckoutSessionCustomField {
    /** The seller's longer explanation of the question, or `null`. */
    description: string | null;
    /** What kind of input to render. `text` today. */
    field_type: CheckoutSessionCustomField.FieldType;
    /** The question's ID, prefixed `field_`. Echo it as the `id` of the matching `custom_field_responses` entry. */
    id: string;
    /** The question as the seller wrote it — the field's label. */
    name: string;
    /** Placeholder text for the input, or `null`. */
    placeholder: string | null;
    /** Whether confirm refuses without an answer. An unanswered required question is refused with `custom_field_invalid`. */
    required: boolean;
}

export namespace CheckoutSessionCustomField {
    /** What kind of input to render. `text` today. */
    export const FieldType = {
        Text: "text",
    } as const;
    export type FieldType = (typeof FieldType)[keyof typeof FieldType];
}
