// This file was auto-generated by Fern from our API Definition.

export interface CheckoutSessionBranding {
    /** Page background, as a `#rrggbb` hex color. */
    background_color: string | null;
    /** `black` or `white`, whichever reads against the background. */
    background_text_color: string | null;
    /** The corner style the seller chose. */
    border_style: CheckoutSessionBranding.BorderStyle | null;
    /** Pay button fill, as a `#rrggbb` hex color. */
    button_color: string | null;
    /** The CSS `border-radius` for buttons at that border style. */
    button_radius: string | null;
    /** `black` or `white`, whichever reads against the button. */
    button_text_color: string | null;
    /** The CSS `border-radius` for containers at that border style. */
    container_radius: string | null;
    /** The font the seller chose. */
    font_family: CheckoutSessionBranding.FontFamily | null;
    /** The stylesheet to load for that font, or `null` for the system font. */
    font_url: string | null;
    /** The CSS `border-radius` for inputs at that border style. */
    input_radius: string | null;
    /** The CSS `font-family` value for that font, or `null` for the system font. */
    resolved_font_family: string | null;
}

export namespace CheckoutSessionBranding {
    /** The corner style the seller chose. */
    export const BorderStyle = {
        Rounded: "rounded",
        Pill: "pill",
        Rectangular: "rectangular",
    } as const;
    export type BorderStyle = (typeof BorderStyle)[keyof typeof BorderStyle];
    /** The font the seller chose. */
    export const FontFamily = {
        System: "system",
        Roboto: "roboto",
        OpenSans: "open_sans",
    } as const;
    export type FontFamily = (typeof FontFamily)[keyof typeof FontFamily];
}
