// This file was auto-generated by Fern from our API Definition.

/**
 * The pixel event optimized for. A standard event, or any custom pixel event name.
 */
export type ConversionEvent =
    | (
          | "purchase"
          | "add_to_cart"
          | "initiated_checkout"
          | "add_payment_info"
          | "complete_registration"
          | "lead"
          | "content_view"
          | "search"
          | "contact"
          | "customize_product"
          | "donate"
          | "find_location"
          | "schedule"
          | "start_trial"
          | "submit_application"
          | "subscribe"
      )
    | string;
