// This file was auto-generated by Fern from our API Definition.

/**
 * A record of a user's progress on a specific lesson, tracking whether they have completed it.
 */
export interface CourseLessonInteraction {
    /** Whether the user has finished this lesson. */
    completed: boolean;
    /** The course that contains the tracked lesson. */
    course: CourseLessonInteraction.Course;
    /** The datetime the lesson interaction was created. */
    created_at: string;
    /** The unique identifier for the lesson interaction. */
    id: string;
    /** The lesson that this progress record belongs to. */
    lesson: CourseLessonInteraction.Lesson;
    /** The user whose progress is being tracked. */
    user: CourseLessonInteraction.User;
}

export namespace CourseLessonInteraction {
    /**
     * The course that contains the tracked lesson.
     */
    export interface Course {
        /** The parent experience that this course belongs to. */
        experience: Course.Experience;
        /** The unique identifier for the course. */
        id: string;
        /** The display name of the course shown to students. Null if no title has been set. */
        title: string | null;
    }

    export namespace Course {
        /**
         * The parent experience that this course belongs to.
         */
        export interface Experience {
            /** The unique identifier for the experience. */
            id: string;
        }
    }

    /**
     * The lesson that this progress record belongs to.
     */
    export interface Lesson {
        /** The parent chapter that contains this lesson. */
        chapter: Lesson.Chapter;
        /** The unique identifier for the lesson. */
        id: string;
        /** The display name of the lesson shown to students. Maximum 120 characters. */
        title: string;
    }

    export namespace Lesson {
        /**
         * The parent chapter that contains this lesson.
         */
        export interface Chapter {
            /** The unique identifier for the chapter. */
            id: string;
        }
    }

    /**
     * The user whose progress is being tracked.
     */
    export interface User {
        /** The unique identifier for the user. */
        id: string;
        /** The user's display name shown on their public profile. */
        name: string | null;
        /** The user's unique username shown on their public profile. */
        username: string;
    }
}
