// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface DisputeEvidenceDocument {
    /** The uploaded file's MIME type. Uploads are restricted to the types the processor accepts. */
    content_type: DisputeEvidenceDocument.ContentType | null;
    /** When the file was created, as an ISO 8601 timestamp. */
    created_at: string;
    /** What kind of evidence the document is. */
    document_type: DisputeEvidenceDocument.DocumentType;
    /** The original filename, including its extension. */
    filename: string | null;
    /** The file's ID, prefixed `file_`. */
    id: string;
    /** The byte size each part (except the last) must be. Present only on create, and only for multipart uploads. */
    multipart_chunk_size?: (number | null) | undefined;
    /** The ID of the multipart upload, passed back to `complete`. Present only on create, and only for multipart uploads. */
    multipart_upload_id?: (string | null) | undefined;
    multipart_upload_urls?: (Whop.FileMultipartUrl[] | null) | undefined;
    /** The type of this object, always `file`. */
    object: string;
    /** The file size in bytes. `null` until the upload has finished. */
    size: number | null;
    /** Headers to send with the upload PUT. Present only on create. */
    upload_headers?: Record<string, unknown> | undefined;
    /** Where the file is in its upload lifecycle. */
    upload_status: DisputeEvidenceDocument.UploadStatus;
    /** Presigned URL to PUT the file's bytes to. Present only on create, and only for single-part uploads. */
    upload_url?: (string | null) | undefined;
    /** A URL to download the file: a permanent CDN URL for public files, a signed expiring URL for private ones. `null` until the upload has finished. */
    url: string | null;
    /** `public` files are served via an unsigned CDN URL; `private` files via a signed, expiring URL. */
    visibility: DisputeEvidenceDocument.Visibility;
}

export namespace DisputeEvidenceDocument {
    /** The uploaded file's MIME type. Uploads are restricted to the types the processor accepts. */
    export const ContentType = {
        ApplicationPdf: "application/pdf",
        ApplicationJson: "application/json",
        ImageJpeg: "image/jpeg",
        ImagePng: "image/png",
        ImageWebp: "image/webp",
    } as const;
    export type ContentType = (typeof ContentType)[keyof typeof ContentType];
    /** What kind of evidence the document is. */
    export const DocumentType = {
        ReturnPolicy: "return_policy",
        ShippingPolicy: "shipping_policy",
        PhysicalFulfillment: "physical_fulfillment",
        CustomerOrderHistory: "customer_order_history",
        ProductImage: "product_image",
        PriorTransactions: "prior_transactions",
        CustomerSession: "customer_session",
        DigitalFulfillment: "digital_fulfillment",
        Subscription: "subscription",
    } as const;
    export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
    /** Where the file is in its upload lifecycle. */
    export const UploadStatus = {
        Pending: "pending",
        Processing: "processing",
        Ready: "ready",
        Failed: "failed",
    } as const;
    export type UploadStatus = (typeof UploadStatus)[keyof typeof UploadStatus];
    /** `public` files are served via an unsigned CDN URL; `private` files via a signed, expiring URL. */
    export const Visibility = {
        Public: "public",
        Private: "private",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
