// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

/**
 * A user's membership record in a messaging channel, including notification preferences and read state.
 */
export interface DmMemberListItem {
    /** The unique identifier of the messaging channel this membership belongs to. */
    channel_id: string;
    /** The unique identifier for the entity */
    id: string;
    /** The timestamp when this member last viewed the channel, as a Unix timestamp in milliseconds. Null if the member has never viewed the channel. */
    last_viewed_at: string | null;
    /** The current state of this membership: requested, accepted, hidden, closed, or archived. */
    status: Whop.DmsFeedMemberStatuses;
    /** The unique identifier of the user who holds this channel membership. */
    user_id: string;
}
