// This file was auto-generated by Fern from our API Definition.

/** The notification preferences for a DMs feed member */
export const DmsFeedMemberNotificationPreferences = {
    All: "all",
    Mentions: "mentions",
    None: "none",
} as const;
export type DmsFeedMemberNotificationPreferences =
    (typeof DmsFeedMemberNotificationPreferences)[keyof typeof DmsFeedMemberNotificationPreferences];
