// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface DomainIssue {
    /** The capability the issue is about. */
    capability: DomainIssue.Capability;
    /** What needs attention, as a stable code. */
    code: DomainIssue.Code;
    dns_records: Whop.DomainDnsRecord[];
    /** What needs attention and how to fix it. */
    message: string;
}

export namespace DomainIssue {
    /** The capability the issue is about. */
    export const Capability = {
        Verification: "verification",
        Registration: "registration",
        Platform: "platform",
        Website: "website",
    } as const;
    export type Capability = (typeof Capability)[keyof typeof Capability];
    /** What needs attention, as a stable code. */
    export const Code = {
        VerificationRequired: "verification_required",
        VerificationExpired: "verification_expired",
        OwnershipConflict: "ownership_conflict",
        OwnershipLost: "ownership_lost",
        DnsRequired: "dns_required",
        ProviderValidation: "provider_validation",
        CertificatePending: "certificate_pending",
        ExpiringSoon: "expiring_soon",
        AccountUnavailable: "account_unavailable",
        CheckFailed: "check_failed",
        PurchaseExpired: "purchase_expired",
        DomainUnavailable: "domain_unavailable",
        PremiumNotSupported: "premium_not_supported",
        UnsupportedTld: "unsupported_tld",
        RegistrationUnavailable: "registration_unavailable",
        RegistrationPremium: "registration_premium",
        RegistrationFailed: "registration_failed",
        RenewalFailed: "renewal_failed",
        PaymentActionRequired: "payment_action_required",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
