// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface DomainRegistrationQuote {
    /** Whether the domain can be registered now. */
    available: boolean;
    /** Whether the registry prices this domain above its standard rate. Premium prices are set per domain and can be much higher. */
    premium: boolean;
    /** What the first year of registration costs. `null` when the domain is not available. */
    price: Whop.Money | null;
    /** A link to this domain's page in your account's Whop dashboard, where you can buy it. `null` when the domain is not available, or when the request has no account, such as a user token without an account context. */
    purchase_url: string | null;
    /** What each yearly renewal costs after the first year. `null` when the domain is not available. */
    renewal_price: Whop.Money | null;
    /** How desirable the domain is, from 0 to 100. Short names that read like real words, on well-known extensions, score highest. Hyphens, digits, random-looking letters, and famous brand names score lower. */
    score: number;
    /** What transferring the domain to Whop costs if you already own it elsewhere, including one added year of registration. `null` when the domain is available or its extension cannot be transferred. */
    transfer_price: Whop.Money | null;
}
