// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface EconomicIntelligence {
    /** ID of the account this recommendation is for, prefixed `biz_`, or null for personal onboarding. */
    account_id: string | null;
    /** Type of action recommended, or `null` when no type is assigned. New values may be added; handle unknown types gracefully. */
    action_type: string | null;
    /** The chat to resume after its initial message is accepted, or null before a chat is ready. */
    ai_chat_id: string | null;
    /** When the recommendation was created, as an ISO 8601 timestamp, or null for an unsaved recommendation. */
    created_at: string | null;
    /** When the recommendation was approved, as an ISO 8601 timestamp, or `null` if it has not been approved. */
    executed_at: string | null;
    expected_tool_calls: Whop.EconomicIntelligenceOperation[] | null;
    /** Recommendation ID, prefixed `reca_`, or `create_business` for an unsaved setup recommendation. Authenticate and list again before executing an unsaved recommendation. */
    id: string;
    /** What you requested, in your own words, or `null` for recommendations generated without your input. */
    input: string | null;
    /** Step-by-step instructions for Whop AI, or `null` when no instructions are available. */
    prompt: string | null;
    /** Evidence and metrics supporting the recommendation, or `null` when no reasoning was provided. */
    reasoning: string | null;
    /** How the user rated this recommendation, or `null` if they have not rated it */
    sentiment: EconomicIntelligence.Sentiment | null;
    /** `queued` when awaiting generation; `pending` while generating; `ready` when available for approval; `executed` when approved; `superseded` when rejected or replaced. */
    status: EconomicIntelligence.Status;
    /** When the recommendation was rejected or replaced, as an ISO 8601 timestamp, or `null` if neither has occurred. */
    superseded_at: string | null;
    /** Website URL selected for pixel setup, or `null` when no website was captured for this recommendation. */
    target_url?: (string | null) | undefined;
    /** Recommended action and its expected benefit, or `null` until generated. */
    title: string | null;
    /** The user's written feedback, or `null` if they have not provided any. */
    user_feedback: string | null;
}

export namespace EconomicIntelligence {
    /** How the user rated this recommendation, or `null` if they have not rated it */
    export const Sentiment = {
        Positive: "positive",
        Negative: "negative",
    } as const;
    export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
    /** `queued` when awaiting generation; `pending` while generating; `ready` when available for approval; `executed` when approved; `superseded` when rejected or replaced. */
    export const Status = {
        Queued: "queued",
        Pending: "pending",
        Ready: "ready",
        Executed: "executed",
        Superseded: "superseded",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
