// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface ExperienceNotificationPreference {
    /** What the user is notified about in the experience: `all` notifications, only `mentions`, or `nothing`. */
    level: ExperienceNotificationPreference.Level;
    /** The type of object. Always `experience_notification_preference`. */
    object: ExperienceNotificationPreference.Object_;
    /** What the preference applies to. Echo it back to `PATCH /users/me/preferences/notifications` to change this preference. */
    scope: Whop.NotificationPreferenceScope;
}

export namespace ExperienceNotificationPreference {
    /** What the user is notified about in the experience: `all` notifications, only `mentions`, or `nothing`. */
    export const Level = {
        All: "all",
        Mentions: "mentions",
        Nothing: "nothing",
    } as const;
    export type Level = (typeof Level)[keyof typeof Level];
    /** The type of object. Always `experience_notification_preference`. */
    export const Object_ = {
        ExperienceNotificationPreference: "experience_notification_preference",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];
}
