// This file was auto-generated by Fern from our API Definition.

export interface FunnelStep {
    /** The Whop app build ID attached to the event. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    app_build_id?: string | undefined;
    /** The event's app id. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    app_id?: string | undefined;
    /** The event's browser. Comma-separated alternatives are ORed; different filters are ANDed. */
    browser?: string | undefined;
    /** The event's city. Comma-separated alternatives are ORed; different filters are ANDed. */
    city?: string | undefined;
    /** The event's country. Comma-separated alternatives are ORed; different filters are ANDed. */
    country?: string | undefined;
    /** The custom event name. Requires event=pixel.custom. Comma-separated alternatives are ORed; different filters are ANDed. */
    custom_name?: string | undefined;
    /** The event's device. Comma-separated alternatives are ORed; different filters are ANDed. */
    device?: string | undefined;
    /** The event name, such as pixel.page, pixel.custom, experiment.exposure, or payment.completed. Exactly one event per step. */
    event: string;
    /** An experiment ID owned by account_id. Requires event=experiment.exposure. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    experiment_id?: string | undefined;
    /** The event's hostname. Comma-separated alternatives are ORed; different filters are ANDed. */
    hostname?: string | undefined;
    /** The event's os. Comma-separated alternatives are ORed; different filters are ANDed. */
    os?: string | undefined;
    /** The URL pathname. Use * to match zero or more characters, including slashes. Other characters match literally. Missing pages do not match. Comma-separated alternatives are ORed; different filters are ANDed. */
    page?: string | undefined;
    /** The plan ID attached to the event. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    plan_id?: string | undefined;
    /** The product ID attached to the event. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    product_id?: string | undefined;
    /** The Whop ad-click source of this page view, not conversion attribution. Use whop:* for any Whop ad click, whop:<campaign>:* for a campaign, or whop:<campaign>:<group>:<ad> for an exact ad. Only ad-click page-view events support source. With breakdown_by=source, trailing :* levels select campaign, ad-group, or ad detail. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    source?: string | undefined;
    /** The event's utm source. Comma-separated alternatives are ORed; different filters are ANDed. */
    utm_source?: string | undefined;
    /** The exposed variant name. Requires event=experiment.exposure. Currently unavailable for funnels; requests return 400. Comma-separated alternatives are ORed; different filters are ANDed. */
    variant?: string | undefined;
}
