// This file was auto-generated by Fern from our API Definition.

export interface NotificationBadge {
    /** Account the experience belongs to, prefixed `biz_`. */
    account_id: string | null;
    /** Experience the badge counts, prefixed `exp_`. */
    experience_id: string;
    /** Whether the caller has unread notifications in this experience. */
    has_unread: boolean;
    /** Number of unread important (mention) notifications in this experience. */
    important_count: number;
    /** When the caller last viewed the experience, as an ISO 8601 timestamp. `null` when never viewed. */
    last_viewed_at: string | null;
}
