// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface Partner {
    /** When the user joined the partner program, as an ISO 8601 timestamp. Null when they have not joined. */
    joined_at: string | null;
    payout_rates: Whop.PartnerPayoutTier[];
    /** Number of active first-tier business referrals attributed to the partner, excluding deleted businesses. */
    referred_businesses_count: number;
    /** The authenticated partner's public profile. */
    user: Whop.UserSummary;
}
