// This file was auto-generated by Fern from our API Definition.

export interface PaymentRuleMatch {
    /** What the rule asked for. */
    action: PaymentRuleMatch.Action;
    /** Payment rule ID, prefixed `prule_`. */
    id: string;
    /** The rule's name when it matched. Renaming the rule afterwards does not rewrite this. */
    name: string | null;
}

export namespace PaymentRuleMatch {
    /** What the rule asked for. */
    export const Action = {
        Allow: "allow",
        Block: "block",
        Review: "review",
        Enforce3Ds: "enforce_3ds",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
}
