// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface PaymentQr {
    /** Exactly what the buyer must pay, in the charged currency. */
    amount?: Whop.Money | undefined;
    /** A hosted page with the complete, printable instructions. If you would rather not render the details yourself, send the buyer here. */
    document_url?: string | undefined;
    /** When the code stops being payable, as an ISO 8601 timestamp. */
    expires_at?: string | undefined;
    /** An account key the buyer can pay to directly (Colombia's Bre-B llave), for apps that take a key instead of a scan. */
    key?: string | undefined;
    /** The QR code's contents, ready to render as a scannable image — `qr_format` says how it is encoded. */
    qr_code?: string | undefined;
    /** How `qr_code` is encoded. */
    qr_format?: string | undefined;
}
