// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface ProductAffiliate {
    /** When the affiliate enrollment was created, as an ISO 8601 timestamp. Includes automatically created enrollments. */
    created_at: string;
    /** Product affiliate ID, prefixed `apaf_`. */
    id: string;
    /** The product the affiliate is enrolled to promote. */
    product: Whop.PromoCodeProduct;
    /** Number of distinct users referred by the affiliate to this product. */
    referred_users_count: number;
    /** Whether the affiliate's enrollment is active or archived. */
    status: ProductAffiliate.Status;
    /** Net rewards earned by the affiliate for this product after fees and reversals, in USD. */
    total_reward_amount_usd: Whop.Money;
    /** The user enrolled as an affiliate. */
    user: Whop.ProductAffiliateUser;
}

export namespace ProductAffiliate {
    /** Whether the affiliate's enrollment is active or archived. */
    export const Status = {
        Active: "active",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
