// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface ResolutionEvent {
    /** The action recorded in this event. */
    action: ResolutionEvent.Action;
    attachments: Whop.ResolutionAttachment[];
    /** When the event occurred, as an ISO 8601 timestamp. */
    created_at: string;
    /** The message body or additional context provided with the event. */
    details: string | null;
    /** Unique identifier for the event, prefixed `revt_`. */
    id: string;
    /** The party that performed the action. */
    reporter_type: ResolutionEvent.ReporterType;
    /** Whether the customer can see this event in the timeline. */
    viewable_by_customer: boolean;
    /** Whether the merchant can see this event in the timeline. */
    viewable_by_merchant: boolean;
}

export namespace ResolutionEvent {
    /** The action recorded in this event. */
    export const Action = {
        Created: "created",
        Responded: "responded",
        Accepted: "accepted",
        Denied: "denied",
        Appealed: "appealed",
        Withdrew: "withdrew",
        RequestedMoreInfo: "requested_more_info",
        Escalated: "escalated",
        DisputeOpened: "dispute_opened",
        DisputeCustomerWon: "dispute_customer_won",
        DisputeMerchantWon: "dispute_merchant_won",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
    /** The party that performed the action. */
    export const ReporterType = {
        Merchant: "merchant",
        Customer: "customer",
        Platform: "platform",
        System: "system",
    } as const;
    export type ReporterType = (typeof ReporterType)[keyof typeof ReporterType];
}
