// This file was auto-generated by Fern from our API Definition.

/** The types of responses the platform can make to a resolution. */
export const ResolutionCenterCasePlatformResponses = {
    RequestBuyerInfo: "request_buyer_info",
    RequestMerchantInfo: "request_merchant_info",
    MerchantWins: "merchant_wins",
    MerchantRefund: "merchant_refund",
} as const;
export type ResolutionCenterCasePlatformResponses =
    (typeof ResolutionCenterCasePlatformResponses)[keyof typeof ResolutionCenterCasePlatformResponses];
