// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface RetrieveStatsRequestSteps {
    "1": Whop.FunnelStep;
    "2": Whop.FunnelStep;
    "3"?: Whop.FunnelStep | undefined;
    "4"?: Whop.FunnelStep | undefined;
    "5"?: Whop.FunnelStep | undefined;
    "6"?: Whop.FunnelStep | undefined;
    "7"?: Whop.FunnelStep | undefined;
    "8"?: Whop.FunnelStep | undefined;
    "9"?: Whop.FunnelStep | undefined;
    "10"?: Whop.FunnelStep | undefined;
}
