// This file was auto-generated by Fern from our API Definition.

export interface StorefrontAccount {
    /** Account ID, prefixed `biz_`. */
    id: string;
    /** Account public route identifier — the `whop.com/{route}` storefront path. */
    route: string;
    /** Account display name. */
    title: string;
}
