// This file was auto-generated by Fern from our API Definition.

export interface TeamMemberAuthorizedRole {
    /** Custom role ID, prefixed `aurl_`. */
    id: string;
    /** Custom role name. */
    name: string;
}
