// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../index.js";

export interface TradingCumulativeFunding {
    /** Funding paid on this market across the account's history, in USD, or `null` when unavailable. */
    all_time: Whop.Money | null;
    /** Funding paid since the position size last changed, in USD, or `null` when unavailable. */
    since_change: Whop.Money | null;
    /** Funding paid since the position opened, in USD, or `null` when unavailable. */
    since_open: Whop.Money | null;
}
