// This file was auto-generated by Fern from our API Definition.

export interface TradingWebsocketSubscription {
    /** The live update stream this subscription opens. */
    channel: TradingWebsocketSubscription.Channel;
    /** JSON subscription message to send unchanged over the Hyperliquid WebSocket. */
    message: string;
}

export namespace TradingWebsocketSubscription {
    /** The live update stream this subscription opens. */
    export const Channel = {
        ClearinghouseState: "clearinghouse_state",
        OpenOrders: "open_orders",
        OrderUpdates: "order_updates",
        UserFills: "user_fills",
        UserEvents: "user_events",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
