// This file was auto-generated by Fern from our API Definition.

/** The different levels of visibility for resources */
export const VisibilityFilter = {
    Visible: "visible",
    Hidden: "hidden",
    Archived: "archived",
    QuickLink: "quick_link",
    All: "all",
    NotQuickLink: "not_quick_link",
    NotArchived: "not_archived",
} as const;
export type VisibilityFilter = (typeof VisibilityFilter)[keyof typeof VisibilityFilter];
