// This file was auto-generated by Fern from our API Definition.

/** The different speeds of withdrawals */
export const WithdrawalSpeeds = {
    Standard: "standard",
    Instant: "instant",
} as const;
export type WithdrawalSpeeds = (typeof WithdrawalSpeeds)[keyof typeof WithdrawalSpeeds];
