// This file was auto-generated by Fern from our API Definition.

export const ListDomainsRequestOrder = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
} as const;
export type ListDomainsRequestOrder = (typeof ListDomainsRequestOrder)[keyof typeof ListDomainsRequestOrder];
