// This file was auto-generated by Fern from our API Definition.

export const ListDomainsRequestStatus = {
    Idle: "idle",
    Pending: "pending",
    Ready: "ready",
    ActionRequired: "action_required",
    Releasing: "releasing",
} as const;
export type ListDomainsRequestStatus = (typeof ListDomainsRequestStatus)[keyof typeof ListDomainsRequestStatus];
