// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "biz_xxxxxxxxxxxxxx",
 *         user_id: "user_xxxxxxxxxxxxx"
 *     }
 */
export interface CreateSupportChannelsRequest {
    /** The unique identifier of the company to create the support channel in. */
    account_id: string;
    /** Optional custom display name for the support channel. */
    custom_name?: string | null;
    /** Whether Whop app notifications are enabled for this support channel. Webhooks still fire. */
    notifications_enabled?: boolean | null;
    /** The user ID (e.g. 'user_xxxxx') or username of the customer to open a support channel for. */
    user_id: string;
}
