// This file was auto-generated by Fern from our API Definition.

export interface ConnectSocialAccountsResponse {
    /** The OAuth authorization URL to redirect the user to. */
    authorize_url: string;
}
