// This file was auto-generated by Fern from our API Definition.

export interface ListLogsResponse {
    data: ListLogsResponse.Data.Item[];
    page_info: ListLogsResponse.PageInfo;
}

export namespace ListLogsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            action: string | null;
            actor: Item.Actor | null;
            created_at: string;
        }

        export namespace Item {
            export interface Actor {
                id: string;
                name?: (string | null) | undefined;
                username?: (string | null) | undefined;
            }
        }
    }

    export interface PageInfo {
        end_cursor: string | null;
        has_next_page: boolean;
        has_previous_page: boolean;
        start_cursor: string | null;
    }
}
