// This file was auto-generated by Fern from our API Definition.

export interface RetrievePayoutsResponse {
    /** The payout amount in whole currency units, as a decimal string. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    amount?: string | undefined;
    /** When the payout was created. */
    created_at: string;
    /** Payout currency. */
    currency: string;
    /** Whether an in-transit withdrawal is past its settlement window. */
    delayed?: boolean | undefined;
    /** The amount delivered in the destination currency, as a decimal string. Assigned when the payout is processed, so it is `null` before then and on payouts without a recorded conversion. */
    destination_amount: string | null;
    /** Currency the funds are delivered in, taken from the payout method when the payout is created. On a stablecoin payout it follows the settlement payout minted alongside it — the `GET /payouts` row carrying this payout's id as `payout_request_id` — and is `null` only when no settlement payout exists. */
    destination_currency: string | null;
    /** Estimated time the funds become available in the destination account. */
    estimated_arrival: string | null;
    /** End of the expected bank settlement window. */
    estimated_arrival_end?: (string | null) | undefined;
    /** Exchange rate from the payout currency to the destination currency. Assigned when the payout is processed, so it is `null` before then and on payouts without a recorded rate. */
    exchange_rate: number | null;
    /** Why the payout ended without paying, or why it reversed after settlement. Present on failed, canceled, denied, and reversed payouts; `null` otherwise. */
    failure: RetrievePayoutsResponse.Failure | null;
    /** The fee charged for the payout, in the payout currency, as a decimal string. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    fee_amount?: string | undefined;
    /** Who bore the payout fee: the account itself, or its parent platform. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    fee_paid_by?: RetrievePayoutsResponse.FeePaidBy | undefined;
    /** Payout ID, prefixed `wdrl_` for a payout returned by `GET /payouts` or `cofr_` for a payout request returned by `POST /payouts`. */
    id: string;
    /** Whop's markup on the provider fee, in the payout currency, as a decimal string. `"0.0"` when none applies. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    markup_fee?: string | undefined;
    /** Key-value data attached at creation and echoed on every read. At most 50 keys, key names up to 40 characters, string values up to 500 characters. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    metadata?: Record<string, string> | undefined;
    /** The planned net for the destination, in the payout currency: amount minus fee_amount minus markup_fee when fee_paid_by is `self`; equal to amount when the platform covers the fees. A payout that ends denied, canceled, or failed delivered nothing — most keep the planned figure and `failure` says where the funds are, but a canceled stablecoin payout can report the settled outcome instead: `amount` carries what stayed in the balance, fees are zero because none were charged, and `net_amount` is 0 because nothing was delivered. */
    net_amount: string;
    /** Free-form notes attached by the payout creator, or `null` when none were provided. Maximum 255 characters. */
    notes: string | null;
    object: RetrievePayoutsResponse.Object_;
    /** Name of the entity processing the payout. */
    payer_name: string | null;
    /** Payout method display details. The nickname requires payout:destination:read on the owning ledger; otherwise it is null. */
    payout_method: RetrievePayoutsResponse.PayoutMethod | null;
    /** Payout request ID, prefixed `cofr_`, returned by `POST /payouts`. For a request retrieved by its own `cofr_` ID, this equals `id`. Returns `null` for payouts not created by `POST /payouts`. */
    payout_request_id: string | null;
    /** The recipient's first name and last initial, or null when no recipient name is available. */
    recipient_name?: (string | null) | undefined;
    /** The sending business's display name, or a personal sender's first name and last initial. */
    sender_name?: (string | null) | undefined;
    /** How the payout was created. `automatic` means a scheduled auto-payout; `null` on payouts created before source tracking or through internal tooling. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    source?: (RetrievePayoutsResponse.Source | null) | undefined;
    /** Payout delivery speed. */
    speed: RetrievePayoutsResponse.Speed;
    /** Text that appears on the recipient's bank statement, or `null` if no descriptor was set. When set, 5-22 alphanumeric characters (A-Z, a-z, 0-9). Only returned to callers with payout:withdrawal:read on the owning ledger. */
    statement_descriptor?: (string | null) | undefined;
    /** Current payout status. */
    status: RetrievePayoutsResponse.Status;
    /** The finest machine phase under `status` — for example `awaiting_provider_acceptance` vs `in_transit` under `processing`, or the stablecoin conversion phase under `requested`. Informational vocabulary: values can be added without a version bump; `status` is the versioned contract. */
    status_detail: string;
    /** Completed lifecycle events in chronological order. Present once the payout has a withdrawal record. */
    timeline?: RetrievePayoutsResponse.Timeline.Item[] | undefined;
    /** ACH trace number the recipient's bank can use to locate this payout. Assigned when the payout is submitted to the bank, so it is `null` before then and on payouts not sent over ACH. */
    trace_code: string | null;
}

export namespace RetrievePayoutsResponse {
    /**
     * Why the payout ended without paying, or why it reversed after settlement. Present on failed, canceled, denied, and reversed payouts; `null` otherwise.
     */
    export interface Failure {
        /** Classified failure code from the maintained error catalog. */
        code: string | null;
        /** The effective time of the reversal that put the funds back in the balance — `null` if they never left it or have not returned yet. Set only once the return is confirmed in the ledger; the ledger posting itself can land moments after this time. */
        funds_returned_at: string | null;
        /** Human-readable explanation of the failure. Callers holding `payout:destination:read` may receive text personalized to the destination; other callers get the generic catalog message. */
        message: string | null;
    }

    /** Who bore the payout fee: the account itself, or its parent platform. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    export const FeePaidBy = {
        Self: "self",
        Platform: "platform",
    } as const;
    export type FeePaidBy = (typeof FeePaidBy)[keyof typeof FeePaidBy];
    export const Object_ = {
        Payout: "payout",
    } as const;
    export type Object_ = (typeof Object_)[keyof typeof Object_];

    /**
     * Payout method display details. The nickname requires payout:destination:read on the owning ledger; otherwise it is null.
     */
    export interface PayoutMethod {
        /** Saved payout method nickname. */
        nickname: string | null;
        /** Supported payout method display details. */
        supported_payout_method: PayoutMethod.SupportedPayoutMethod | null;
    }

    export namespace PayoutMethod {
        /**
         * Supported payout method display details.
         */
        export interface SupportedPayoutMethod {
            /** How the funds are delivered to the recipient. */
            delivery_type: SupportedPayoutMethod.DeliveryType;
            /** Supported payout method icon URL. */
            icon_url: string | null;
            /** Supported payout method display name. */
            payer_name: string | null;
        }

        export namespace SupportedPayoutMethod {
            /** How the funds are delivered to the recipient. */
            export const DeliveryType = {
                CashPickup: "cash_pickup",
                BankDeposit: "bank_deposit",
                HomeDelivery: "home_delivery",
                MobileWallet: "mobile_wallet",
                Card: "card",
                Check: "check",
                Bill: "bill",
                Cryptocurrency: "cryptocurrency",
                Unknown: "unknown",
            } as const;
            export type DeliveryType = (typeof DeliveryType)[keyof typeof DeliveryType];
        }
    }

    /** How the payout was created. `automatic` means a scheduled auto-payout; `null` on payouts created before source tracking or through internal tooling. Only returned to callers with payout:withdrawal:read on the owning ledger. */
    export const Source = {
        Api: "api",
        Dashboard: "dashboard",
        Automatic: "automatic",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
    /** Payout delivery speed. */
    export const Speed = {
        Standard: "standard",
        Instant: "instant",
    } as const;
    export type Speed = (typeof Speed)[keyof typeof Speed];
    /** Current payout status. */
    export const Status = {
        Requested: "requested",
        InReview: "in_review",
        Processing: "processing",
        Completed: "completed",
        Reversed: "reversed",
        Canceled: "canceled",
        Failed: "failed",
        Denied: "denied",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Timeline = Timeline.Item[];

    export namespace Timeline {
        export interface Item {
            /** Failure message, only with payout:destination:read. */
            error_message: string | null;
            estimated_arrival: string | null;
            status: Item.Status;
            /** Informational event detail; security_review identifies manual review. */
            status_detail: string | null;
            timestamp: string | null;
        }

        export namespace Item {
            export const Status = {
                Requested: "requested",
                AwaitingPayment: "awaiting_payment",
                InTransit: "in_transit",
                Completed: "completed",
                Failed: "failed",
                Canceled: "canceled",
                Denied: "denied",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
