// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../index.js";

export interface PostAdUpdatedPayload {
    /** The account ID that this webhook event is associated with */
    account_id?: (string | null) | undefined;
    /** The API version for this webhook */
    api_version: PostAdUpdatedPayload.ApiVersion;
    /** The dated API version (Api-Version-Date) the payload is serialized to */
    api_version_date: string | null;
    data: PostAdUpdatedPayload.Data;
    /** A unique ID for every single webhook request */
    id: string;
    /** For some `.updated` events, the old values of the payload fields that changed, keyed by field name. Omitted when no capture is available for the event */
    previous_attributes?: Record<string, unknown> | undefined;
    /** The timestamp in ISO 8601 format that the webhook was sent at on the server */
    timestamp: string;
    /** The webhook event type */
    type: PostAdUpdatedPayload.Type;
}

export namespace PostAdUpdatedPayload {
    /** The API version for this webhook */
    export const ApiVersion = {
        V1: "v1",
    } as const;
    export type ApiVersion = (typeof ApiVersion)[keyof typeof ApiVersion];

    export interface Data {
        /** The ad campaign this ad belongs to. */
        ad_campaign: Whop.AdEntityReference;
        /** The ad group this ad belongs to. */
        ad_group: Whop.AdEntityReference;
        /** The call-to-action button shown on the ad. */
        call_to_action: Data.CallToAction | null;
        /** When the ad was created, as an ISO 8601 timestamp. */
        created_at: string;
        creatives: Whop.AdCreative[];
        /** Whether the ad is delivering right now, and if not, why. When several states apply at once, the highest-precedence one is returned. */
        delivery_status: Data.DeliveryStatus;
        descriptions: string[];
        /** The post you pointed this ad at, when it promotes one you already published — a Facebook post, Instagram media, or TikTok video ID. `null` when the ad uses uploaded creatives. */
        existing_post_id: string | null;
        headlines: string[];
        /** Unique identifier for the ad, prefixed `ad_`. */
        id: string;
        issues: Whop.AdPlatformIssue[];
        /** The instant lead form shown when someone taps this ad. `null` when the ad group's conversion_location is not an instant-form destination. */
        lead_form?: (Whop.AdLeadForm | null) | undefined;
        /** The ad platform's ID for the instant form the ad uses. Set when the ad references an existing form via `lead_form_id`, or once a form built from `lead_form` has been created on the platform. */
        lead_form_id?: (string | null) | undefined;
        /** Welcome message for click-to-message ads, shown when the conversation opens. `null` when the ad has none. */
        messaging_config?: (Whop.AdMessagingConfig | null) | undefined;
        /** Whether the ad can appear alongside other advertisers' ads in the same unit. Defaults to true. */
        multi_advertiser_ads?: boolean | undefined;
        /** The advertiser-uploaded MP3 a TikTok carousel ad plays. TikTok-only; `null` elsewhere and for non-carousel ads. */
        music?: (Whop.AdMusic | null) | undefined;
        /** The post the ad network serves for this ad, as `pageID_postID` on Meta — the post Meta created for an uploaded creative, or the post being promoted. Use it to open the live post, or to promote the same post from another ad. `null` until the network has created the post. */
        post_id: string | null;
        /** Identifies the network that owns `existing_post_id`; `null` when the ad uses uploaded creatives. */
        post_source: Data.PostSource | null;
        /** Preview image of the post named by `existing_post_id`. `null` for ads that use uploaded creatives, or until the post's media has been fetched from the network. */
        post_thumbnail_url: string | null;
        primary_texts: string[];
        social_accounts: Whop.AdEntityReference[];
        /** Whether the ad is enabled. `active` and `paused` are set by you; `in_review` and `rejected` come from ad review. */
        status: Data.Status;
        /** Display title of the ad. */
        title: string | null;
        /** When the ad was last updated, as an ISO 8601 timestamp. */
        updated_at: string;
        /** The URL the ad links to, without its query string. Parameters belong in `url_parameters`; any you send on `url` are moved there. */
        url: string | null;
        /** Every query parameter appended to the URL, keyed by parameter name — including any you sent on `url` itself. Whop adds its own click-attribution parameters on top; those are reserved and rejected if you set them. Which keys are reserved depends on the ad's network — Meta: utm_meta_ad_id, utm_meta_adset_id, utm_meta_campaign_id, utm_source, utm_placement, utm_medium, utm_content, utm_adset, utm_whop, wacid, wasid, waid, tw_source, tw_adid; TikTok: waid, wasid, wacid, ad_id, adset_id, campaign_id, utm_source, utm_medium, utm_placement, utm_whop, tw_source, tw_adid. */
        url_parameters: Record<string, unknown>;
    }

    export namespace Data {
        /** The call-to-action button shown on the ad. */
        export const CallToAction = {
            LearnMore: "learn_more",
            ShopNow: "shop_now",
            SignUp: "sign_up",
            Subscribe: "subscribe",
            GetStarted: "get_started",
            BookNow: "book_now",
            ApplyNow: "apply_now",
            ContactUs: "contact_us",
            Download: "download",
            OrderNow: "order_now",
            BuyNow: "buy_now",
            GetQuote: "get_quote",
            MessagePage: "message_page",
            WhatsappMessage: "whatsapp_message",
            InstagramMessage: "instagram_message",
            CallNow: "call_now",
            GetDirections: "get_directions",
            SendUpdates: "send_updates",
            GetOffer: "get_offer",
            WatchMore: "watch_more",
            ListenNow: "listen_now",
            PlayGame: "play_game",
            OpenLink: "open_link",
            NoButton: "no_button",
            GetOfferView: "get_offer_view",
            GetEventTickets: "get_event_tickets",
            SeeMenu: "see_menu",
            RequestTime: "request_time",
            EventRsvp: "event_rsvp",
            SeeDetails: "see_details",
            ViewInstagramProfile: "view_instagram_profile",
        } as const;
        export type CallToAction = (typeof CallToAction)[keyof typeof CallToAction];
        /** Whether the ad is delivering right now, and if not, why. When several states apply at once, the highest-precedence one is returned. */
        export const DeliveryStatus = {
            Rejected: "rejected",
            InReview: "in_review",
            Draft: "draft",
            CampaignPaused: "campaign_paused",
            AdGroupPaused: "ad_group_paused",
            Paused: "paused",
            Processing: "processing",
            Issues: "issues",
            Scheduled: "scheduled",
            LearningLimited: "learning_limited",
            Learning: "learning",
            Active: "active",
        } as const;
        export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus];
        /** Identifies the network that owns `existing_post_id`; `null` when the ad uses uploaded creatives. */
        export const PostSource = {
            Facebook: "facebook",
            Instagram: "instagram",
        } as const;
        export type PostSource = (typeof PostSource)[keyof typeof PostSource];
        /** Whether the ad is enabled. `active` and `paused` are set by you; `in_review` and `rejected` come from ad review. */
        export const Status = {
            Active: "active",
            Paused: "paused",
            InReview: "in_review",
            Rejected: "rejected",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }

    /** The webhook event type */
    export const Type = {
        AdUpdated: "ad.updated",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
