// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface RetrievePreferencesRequest {
    /** Account ID, prefixed `biz_`. */
    account_id: string;
}
