// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface UpdatePreferencesRequest {
    /** Account ID, prefixed `biz_`. */
    account_id: string;
    /** Opens an advertising certification application. Keyed by certification type (`prescription_drug_ads`); set the entry's `status` to `pending_information` to start, then answer the requested fields via `PATCH /verifications/{id}`. Only one application per type can be open at a time; every other status is set by Whop's review. Requires the `ad_campaign:create` scope on your API key. */
    ads_certifications?: Record<string, UpdatePreferencesRequest.AdsCertifications.Value>;
    /** How the account pays for Whop Ads spend. Requires `primary`; `backup` is optional and covers the charge when the primary fails. Requires the `ad_campaign:create` scope on your API key. Configuring a `card` requires a user token; account API keys can configure only `platform_balance` sources. */
    ads_payment_methods?: UpdatePreferencesRequest.AdsPaymentMethods;
    /** Lowercase ISO currency code, such as `usd` or `eur`, used to display ad spend and stats. Defaults to `usd`. Requires the `ad_campaign:create` scope on your API key. */
    ads_reporting_currency?: string;
    /** IANA timezone (e.g. `America/New_York`) used to interpret campaign start/end times and to bucket reports. Cannot be cleared once set — pass a new value to change it. Requires the `ad_campaign:create` scope on your API key. */
    ads_scheduling_timezone?: string;
    /** Connects or disconnects the Triple Whale integration, or changes the shop it reports to. Requires the `ad_campaign:create` scope on your API key. Connecting requires a shop domain to report spend against — either an explicit `shop_domain` (required for any merchant without a connected Shopify store, e.g. WooCommerce, a custom checkout, or a white-label platform's merchant) or a Shopify store connected on the Fulfillment page. */
    ads_triple_whale_integration?: UpdatePreferencesRequest.AdsTripleWhaleIntegration;
    /** Whether incoming funds are automatically moved to the account's cards balance. Requires a cards balance on the account and the `payout:account:update` scope on your API key. */
    cards_auto_top_up?: boolean;
    /** Whether Whop Card notifications reach this account's team. Set it to `false` to stop every card email and push notification for the account — application status, verification and action-required alerts, card-ready alerts, declines, large charges, and cashback summaries. Cardholder onboarding invitations still send, because they carry the only link an invited cardholder can onboard with. Requesting a card is rejected while notifications are off, since the request reaches nobody. Cards on personal accounts are unaffected. Requires a cards balance on the account and the `payout:account:update` scope on your API key. */
    cards_notifications?: boolean;
    /** Whether Whop assembles and files the evidence response when this account's payments are disputed. Off by default; enabling it also opts the account into the success fee charged only on disputes it wins. Requires the `payment:dispute` scope on your API key. */
    dispute_fighter_enabled?: boolean;
    /** Turns on Economic Intelligence for the duration with this `key` in `economic_intelligence_offers`, at that duration's fee. It can't be changed or turned off until `economic_intelligence_ends_at`, and it can only be turned on once the account is off the Economic Intelligence waitlist. Requires the `company:update` scope on your API key. */
    economic_intelligence_duration_key?: UpdatePreferencesRequest.EconomicIntelligenceDurationKey;
    /** What happens to a subscription once every retry of a renewal payment has failed. `cancel` (the default) cancels it. `none` leaves it past due and keeps billing it each period; access follows the account's past-due access setting. Requires company:manage_checkout permission. */
    subscription_failure_behavior?: UpdatePreferencesRequest.SubscriptionFailureBehavior;
}

export namespace UpdatePreferencesRequest {
    export namespace AdsCertifications {
        export interface Value {
            /** Must be `pending_information`. */
            status: Value.Status;
        }

        export namespace Value {
            /** Must be `pending_information`. */
            export const Status = {
                PendingInformation: "pending_information",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }

    /**
     * How the account pays for Whop Ads spend. Requires `primary`; `backup` is optional and covers the charge when the primary fails. Requires the `ad_campaign:create` scope on your API key. Configuring a `card` requires a user token; account API keys can configure only `platform_balance` sources.
     */
    export interface AdsPaymentMethods {
        /** Optional second method charged if the primary fails. Any pairing is allowed (two cards, card+balance, balance+card); omit it to run on a single method. Must differ from the primary. */
        backup?: AdsPaymentMethods.Backup | undefined;
        primary: AdsPaymentMethods.Primary;
    }

    export namespace AdsPaymentMethods {
        /**
         * Optional second method charged if the primary fails. Any pairing is allowed (two cards, card+balance, balance+card); omit it to run on a single method. Must differ from the primary.
         */
        export interface Backup {
            /** The funding source ID: a Whop balance (`ldgr_`) for `platform_balance`, or a payment method (`payt_`) for `card`. Optional for `platform_balance` — defaults to the account's default Whop balance. Required for `card`. */
            id?: string | undefined;
            /** The funding source kind. */
            type: Backup.Type;
        }

        export namespace Backup {
            /** The funding source kind. */
            export const Type = {
                PlatformBalance: "platform_balance",
                Card: "card",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }

        export interface Primary {
            /** The funding source ID: a Whop balance (`ldgr_`) for `platform_balance`, or a payment method (`payt_`) for `card`. Optional for `platform_balance` — defaults to the account's default Whop balance. Required for `card`. */
            id?: string | undefined;
            /** The funding source kind. */
            type: Primary.Type;
        }

        export namespace Primary {
            /** The funding source kind. */
            export const Type = {
                PlatformBalance: "platform_balance",
                Card: "card",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }

    /**
     * Connects or disconnects the Triple Whale integration, or changes the shop it reports to. Requires the `ad_campaign:create` scope on your API key. Connecting requires a shop domain to report spend against — either an explicit `shop_domain` (required for any merchant without a connected Shopify store, e.g. WooCommerce, a custom checkout, or a white-label platform's merchant) or a Shopify store connected on the Fulfillment page.
     */
    export interface AdsTripleWhaleIntegration {
        /** A Triple Whale Data-In API key with the `Ads: Write` scope, validated against Triple Whale before it is stored. Pass `null` to disconnect. Connecting for the first time backfills the account's existing ad spend. Required unless you are only changing `shop_domain` on an already connected integration, in which case the stored key is reused. */
        api_key?: (string | null) | undefined;
        /** The exact shop domain configured in Triple Whale's Settings → Store (for Shopify this is the `.myshopify.com` domain; for a custom sales platform it's whatever domain Triple Whale assigned when the shop was set up there). A leading `https://` and trailing `/` are stripped, and what remains must be a bare hostname with no path or spaces. Validated against Triple Whale — the API key must have access to it — before it is stored. Changing it on a connected integration backfills the account's ad spend onto the new shop. Omit to fall back to a connected Shopify store's domain; there is no way to clear a stored value, only to overwrite it with a new domain. */
        shop_domain?: string | undefined;
    }

    /** Turns on Economic Intelligence for the duration with this `key` in `economic_intelligence_offers`, at that duration's fee. It can't be changed or turned off until `economic_intelligence_ends_at`, and it can only be turned on once the account is off the Economic Intelligence waitlist. Requires the `company:update` scope on your API key. */
    export const EconomicIntelligenceDurationKey = {
        SevenDays: "7_days",
        OneDay: "1_day",
        OneHour: "1_hour",
    } as const;
    export type EconomicIntelligenceDurationKey =
        (typeof EconomicIntelligenceDurationKey)[keyof typeof EconomicIntelligenceDurationKey];
    /** What happens to a subscription once every retry of a renewal payment has failed. `cancel` (the default) cancels it. `none` leaves it past due and keeps billing it each period; access follows the account's past-due access setting. Requires company:manage_checkout permission. */
    export const SubscriptionFailureBehavior = {
        Cancel: "cancel",
        None: "none",
    } as const;
    export type SubscriptionFailureBehavior =
        (typeof SubscriptionFailureBehavior)[keyof typeof SubscriptionFailureBehavior];
}
