// This file was auto-generated by Fern from our API Definition.

export const ListAdConversionValueRulesRequestPlatform = {
    Tiktok: "tiktok",
    Meta: "meta",
    Google: "google",
} as const;
export type ListAdConversionValueRulesRequestPlatform =
    (typeof ListAdConversionValueRulesRequestPlatform)[keyof typeof ListAdConversionValueRulesRequestPlatform];
