// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListNotificationsRequest {
    /** Only return notifications created since the user last viewed their source. */
    unread?: boolean;
    /** Only return notifications from this experience (`exp_` tag). */
    experience_id?: string;
    /** Only return team notifications for this account (`biz_` tag). */
    account_id?: string;
    /** Only return notifications that mention the user directly. */
    mentions?: boolean;
    /** The number of notifications to return (default 20, max 100). */
    first?: number;
    /** A cursor (a notification `id` from a previous page); returns notifications older than it. */
    after?: string;
}
