// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         payment_id: "payment_id",
 *         return_url: "https://shinetime.example/checkout/thanks"
 *     }
 */
export interface UpdateReturnUrlPaymentsRequest {
    /** The unique identifier of the payment. */
    payment_id: string;
    /** Where the buyer continues after completing an off-site step. Must be an absolute https URL without credentials (http is allowed for localhost), at most 2,048 characters. */
    return_url: string;
}
