// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "inv_xxxxxxxxxxxxxx"
 *     }
 */
export interface RetrieveInvoicesRequest {
    /** The unique identifier of the invoice, or a secure token. */
    id: string;
}
