// This file was auto-generated by Fern from our API Definition.

export const SummaryResolutionCenterCasesRequestReasonItem = {
    Fraudulent: "fraudulent",
    ProductNotReceived: "product_not_received",
    NotAsDescribed: "not_as_described",
    ProductUnacceptable: "product_unacceptable",
    SubscriptionCanceled: "subscription_canceled",
} as const;
export type SummaryResolutionCenterCasesRequestReasonItem =
    (typeof SummaryResolutionCenterCasesRequestReasonItem)[keyof typeof SummaryResolutionCenterCasesRequestReasonItem];
