// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateCardsRequest {
    /** Card ID to retrieve, prefixed `icrd_`. */
    id: string;
    /** The owning account ID (a biz_ identifier). Provide this or user_id. */
    account_id?: string;
    /** The billing address. On an issued card this replaces the card's billing address and region is also required. On an invited card, sending it as the invited user completes onboarding and starts card provisioning. */
    billing?: UpdateCardsRequest.Billing;
    /** Pass `true` to permanently cancel the card. A canceled card cannot be uncanceled. Cannot be combined with other fields. */
    canceled?: boolean;
    /** Details for the invited cardholder, accepted only while completing onboarding on an invited card. The legal name comes from an approved identity verification when the invited user has one, and from these fields when they do not. */
    cardholder?: UpdateCardsRequest.Cardholder;
    /** Pass `true` to freeze the card, `false` to unfreeze it. The assigned cardholder may freeze their own card without the payout:account:update scope. */
    frozen?: boolean;
    /** A display name for the card. */
    name?: string;
    /** New 4-digit PIN. Can only be set on a card assigned to the acting user, who may set it without the payout:account:update scope. */
    pin?: string;
    /** Pass `true` to remove the spending limit (make the card unlimited). */
    remove_limit?: boolean;
    /** Spending limit amount, in dollars. */
    spend_limit?: number;
    /** The window the spend limit applies to. */
    spend_limit_frequency?: UpdateCardsRequest.SpendLimitFrequency;
    /** Per-transaction limit amount, in dollars. */
    transaction_limit?: number;
    /** The owning user ID (a user_ identifier). Provide this or account_id. */
    user_id?: string;
}

export namespace UpdateCardsRequest {
    /**
     * The billing address. On an issued card this replaces the card's billing address and region is also required. On an invited card, sending it as the invited user completes onboarding and starts card provisioning.
     */
    export interface Billing {
        /** Billing city. */
        city: string;
        /** Billing country code, ISO 3166-1 alpha-2. */
        country_code: string;
        /** Street address line 1. */
        line1: string;
        /** Street address line 2. */
        line2?: string | undefined;
        /** Billing postal code. */
        postal_code: string;
        /** Billing region or state. Required when updating an issued card's billing address. */
        region?: string | undefined;
    }

    /**
     * Details for the invited cardholder, accepted only while completing onboarding on an invited card. The legal name comes from an approved identity verification when the invited user has one, and from these fields when they do not.
     */
    export interface Cardholder {
        /** Email address for the invited cardholder. */
        email?: string | undefined;
        /** Legal first name of the invited cardholder. */
        first_name?: string | undefined;
        /** Legal last name of the invited cardholder. */
        last_name?: string | undefined;
        /** Phone number for the invited cardholder. */
        phone?: string | undefined;
    }

    /** The window the spend limit applies to. */
    export const SpendLimitFrequency = {
        Daily: "daily",
        Weekly: "weekly",
        Monthly: "monthly",
        OneTime: "one_time",
    } as const;
    export type SpendLimitFrequency = (typeof SpendLimitFrequency)[keyof typeof SpendLimitFrequency];
}
