// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DuplicateAdGroupsRequest {
    /** The ad group ID. */
    id: string;
    /** Number of copies to create (1-10). Defaults to 1. */
    count?: number;
    /** Whether the copied ads keep the original posts' engagement (likes, comments, shares). Defaults to false. */
    preserve_engagement?: boolean;
    /** Campaign to duplicate into. Defaults to the ad group's own campaign. */
    target_ad_campaign_id?: string;
}
