export { CreateAdGroupsRequest } from "./CreateAdGroupsRequest.js";
export type { DeleteAdGroupsRequest } from "./DeleteAdGroupsRequest.js";
export type { DuplicateAdGroupsRequest } from "./DuplicateAdGroupsRequest.js";
export { EstimateReachAdGroupsRequest } from "./EstimateReachAdGroupsRequest.js";
export type { ListAdGroupsRequest } from "./ListAdGroupsRequest.js";
export type { PauseAdGroupsRequest } from "./PauseAdGroupsRequest.js";
export type { RetrieveAdGroupsRequest } from "./RetrieveAdGroupsRequest.js";
export type { SearchTargetingOptionsAdGroupsRequest } from "./SearchTargetingOptionsAdGroupsRequest.js";
export type { UnpauseAdGroupsRequest } from "./UnpauseAdGroupsRequest.js";
export { UpdateAdGroupsRequest } from "./UpdateAdGroupsRequest.js";
