// This file was auto-generated by Fern from our API Definition.

export interface ChallengePasskeysResponse {
    /** The challenge to pass to the WebAuthn ceremony, base64url-encoded without padding. */
    challenge: string;
}
