// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {
 *         app_id: "app_id"
 *     }
 */
export interface ListAppBuildsRequest {
    /** The app to list builds for, prefixed `app_`. */
    app_id: string;
    /** Filter builds by target platform. */
    platform?: Whop.ListAppBuildsRequestPlatform;
    /** Filter builds by review status. */
    status?: Whop.ListAppBuildsRequestStatus;
    /** Only return builds created before this ISO 8601 timestamp. */
    created_before?: Whop.ListAppBuildsRequestCreatedBefore;
    /** Only return builds created after this ISO 8601 timestamp. */
    created_after?: Whop.ListAppBuildsRequestCreatedAfter;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
    /** Number of results to return from the end of the range. */
    last?: number;
    /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
    before?: string;
}
