// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Whop from "../../../index.js";

export declare namespace DmMembersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DmMembersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DmMembersClient.Options>;

    constructor(options: DmMembersClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of members in a specific DM channel, sorted by the date they were added.
     *
     * Required permissions (one of):
     *  - `dms:read`
     *  - `support_chat:read`
     *
     * @param {Whop.ListDmMembersRequest} request
     * @param {DmMembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.UnprocessableEntityError}
     * @throws {@link Whop.TooManyRequestsError}
     * @throws {@link Whop.InternalServerError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.dmMembers.list({
     *         first: 42,
     *         last: 42,
     *         channel_id: "channel_id"
     *     })
     */
    public async list(
        request: Whop.ListDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): Promise<core.Page<Whop.DmMemberListItem, Whop.ListDmMembersResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Whop.ListDmMembersRequest): Promise<core.WithRawResponse<Whop.ListDmMembersResponse>> => {
                const { after, before, first, last, channel_id: channelId } = request;
                const _queryParams: Record<string, unknown> = {
                    after,
                    before,
                    first,
                    last,
                    channel_id: channelId,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        "Api-Version-Date":
                            requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-2",
                        "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.WhopEnvironment.Default,
                        "dm_members",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Whop.ListDmMembersResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                        case 401:
                            throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                        case 403:
                            throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 404:
                            throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                        case 422:
                            throw new Whop.UnprocessableEntityError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Whop.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                        case 500:
                            throw new Whop.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                        default:
                            throw new errors.WhopError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/dm_members");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Whop.DmMemberListItem, Whop.ListDmMembersResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.page_info.end_cursor != null &&
                !(typeof response?.page_info.end_cursor === "string" && response?.page_info.end_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "after", response?.page_info.end_cursor));
            },
        });
    }

    /**
     * Add a new user to an existing DM channel. Only an admin of the channel can add members.
     *
     * Required permissions (one of):
     *  - `dms:message:manage`
     *  - `support_chat:message:create`
     *
     * @param {Whop.CreateDmMembersRequest} request
     * @param {DmMembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.UnprocessableEntityError}
     * @throws {@link Whop.TooManyRequestsError}
     * @throws {@link Whop.InternalServerError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.dmMembers.create({
     *         channel_id: "channel_id",
     *         user_id: "user_xxxxxxxxxxxxx"
     *     })
     */
    public create(
        request: Whop.CreateDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.DmMember> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Whop.CreateDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.DmMember>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                "dm_members",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.DmMember, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Whop.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Whop.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Whop.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/dm_members");
    }

    /**
     * Retrieves the details of an existing DM member.
     *
     * Required permissions (one of):
     *  - `dms:read`
     *  - `support_chat:read`
     *
     * @param {Whop.RetrieveDmMembersRequest} request
     * @param {DmMembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.UnprocessableEntityError}
     * @throws {@link Whop.TooManyRequestsError}
     * @throws {@link Whop.InternalServerError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.dmMembers.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Whop.RetrieveDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.DmMember> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Whop.RetrieveDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.DmMember>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `dm_members/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.DmMember, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Whop.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Whop.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Whop.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/dm_members/{id}");
    }

    /**
     * Remove a user from a DM channel. An admin can remove any member, and a member can remove themselves.
     *
     * Required permissions (one of):
     *  - `dms:read`
     *  - `support_chat:read`
     *
     * @param {Whop.DeleteDmMembersRequest} request
     * @param {DmMembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.UnprocessableEntityError}
     * @throws {@link Whop.TooManyRequestsError}
     * @throws {@link Whop.InternalServerError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.dmMembers.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Whop.DeleteDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): core.HttpResponsePromise<boolean> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Whop.DeleteDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<boolean>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `dm_members/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as boolean, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Whop.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Whop.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Whop.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/dm_members/{id}");
    }

    /**
     * Update a DM channel member's settings, such as their notification preferences or membership status.
     *
     * Required permissions (one of):
     *  - `dms:read`
     *  - `support_chat:read`
     *
     * @param {Whop.UpdateDmMembersRequest} request
     * @param {DmMembersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link Whop.UnprocessableEntityError}
     * @throws {@link Whop.TooManyRequestsError}
     * @throws {@link Whop.InternalServerError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.dmMembers.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Whop.UpdateDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.DmMember> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Whop.UpdateDmMembersRequest,
        requestOptions?: DmMembersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.DmMember>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-09-02-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WhopEnvironment.Default,
                `dm_members/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.DmMember, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Whop.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Whop.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Whop.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/dm_members/{id}");
    }
}
