// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../../index.js";

export interface PlatformTrendsReportsResponse {
    data: PlatformTrendsReportsResponse.Data;
    page_info: PlatformTrendsReportsResponse.PageInfo;
}

export namespace PlatformTrendsReportsResponse {
    export interface Data {
        /** What each row is, or `null` for one total row per window. */
        breakdown_by: string | null;
        /** The breakdown first, then each requested property and metric, in row order. */
        columns: Data.Columns.Item[];
        /** When the data was read, as an ISO 8601 timestamp. */
        data_as_of: string;
        /** The report's key. */
        report: string;
        /** One entry per requested window, in request order. Rows line up by index across entries. */
        reports: Data.Reports.Item[];
    }

    export namespace Data {
        export type Columns = Columns.Item[];

        export namespace Columns {
            export interface Item {
                /** Metrics only. How to combine the metric across rows. */
                aggregate?: Item.Aggregate | undefined;
                /** The column's key on each row. */
                key: string;
                /** The column's display name. */
                name: string;
                /** An attribute of the row, or a number measured over it. */
                type: Item.Type;
                /** Metrics only. Sets the value's JSON type. */
                unit?: Item.Unit | undefined;
                /** Metrics only. The column an `average` metric is weighted by. */
                weight?: (string | null) | undefined;
            }

            export namespace Item {
                /** Metrics only. How to combine the metric across rows. */
                export const Aggregate = {
                    Sum: "sum",
                    Average: "average",
                    None: "none",
                } as const;
                export type Aggregate = (typeof Aggregate)[keyof typeof Aggregate];
                /** An attribute of the row, or a number measured over it. */
                export const Type = {
                    Property: "property",
                    Metric: "metric",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];
                /** Metrics only. Sets the value's JSON type. */
                export const Unit = {
                    Money: "money",
                    Count: "count",
                    Rate: "rate",
                    Months: "months",
                    Years: "years",
                } as const;
                export type Unit = (typeof Unit)[keyof typeof Unit];
            }
        }

        export type Reports = Reports.Item[];

        export namespace Reports {
            export interface Item {
                /** The page of rows. Only the requested columns are present. */
                rows: Item.Rows.Item[];
                window: Item.Window;
            }

            export namespace Item {
                export type Rows = Rows.Item[];

                export namespace Rows {
                    export interface Item {
                        account_country?: (Item.AccountCountry | null) | undefined;
                        /** Gross revenue per payment. */
                        aov?: (Whop.Money | null) | undefined;
                        /** Average age in months of the businesses that sold. */
                        avg_business_age?: (number | null) | undefined;
                        /** Average age in years of the paying customers. */
                        avg_customer_age?: (number | null) | undefined;
                        /** Average age in years of those businesses' owners. */
                        avg_owner_age?: (number | null) | undefined;
                        business_type?: (Item.BusinessType | null) | undefined;
                        /** Businesses with a paid payment. */
                        businesses?: (number | null) | undefined;
                        customer_country?: (Item.CustomerCountry | null) | undefined;
                        /** Distinct paying customers. A customer who pays in two groups counts in both. */
                        customers?: (number | null) | undefined;
                        /** Paid sales, before refunds and fees, measured the way an account's gross revenue is. */
                        gross_revenue?: (Whop.Money | null) | undefined;
                        industry_type?: (Item.IndustryType | null) | undefined;
                        /** The median paid volume per business that sold. */
                        median_gross_revenue?: (Whop.Money | null) | undefined;
                        /** Businesses created in the window that also sold in it. */
                        new_businesses?: (number | null) | undefined;
                        /** Paid payments. */
                        payments?: (number | null) | undefined;
                        /** Share of customers who paid more than once, as a fraction. */
                        repeat_rate?: (number | null) | undefined;
                    }

                    export namespace Item {
                        export interface AccountCountry {
                            /** The value's id, such as `options_trading`. */
                            id: string;
                            /** The value's display name. */
                            name: string;
                        }

                        export interface BusinessType {
                            /** The value's id, such as `options_trading`. */
                            id: string;
                            /** The value's display name. */
                            name: string;
                        }

                        export interface CustomerCountry {
                            /** The value's id, such as `options_trading`. */
                            id: string;
                            /** The value's display name. */
                            name: string;
                        }

                        export interface IndustryType {
                            /** The value's id, such as `options_trading`. */
                            id: string;
                            /** The value's display name. */
                            name: string;
                        }
                    }
                }

                export interface Window {
                    /** Always `null` for a range window. */
                    as_of: string | null;
                    /** Start of the data that answered the window, as an ISO 8601 timestamp. `null` for `all_time`. */
                    from: string | null;
                    /** The window as requested, such as `30d` or `prev:7d`. */
                    key: string;
                    /** Always `range` for this report. */
                    kind: Window.Kind;
                    /** The zone the window's boundaries fall in. */
                    time_zone: string;
                    /** End of the data that answered the window, exclusive, as an ISO 8601 timestamp. */
                    to: string | null;
                }

                export namespace Window {
                    /** Always `range` for this report. */
                    export const Kind = {
                        Range: "range",
                    } as const;
                    export type Kind = (typeof Kind)[keyof typeof Kind];
                }
            }
        }
    }

    export interface PageInfo {
        /** Pass as `after` for the next page. */
        end_cursor: string | null;
        /** Whether more rows follow this page. */
        has_next_page: boolean;
        /** Whether rows precede this page. */
        has_previous_page: boolean;
        /** The cursor of the first row on this page. */
        start_cursor: string | null;
    }
}
