// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "file_xxxxxxxxxxxxx"
 *     }
 */
export interface RetrieveFilesRequest {
    /** The unique identifier of the file to retrieve. */
    id: string;
}
