// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         first: 42,
 *         last: 42,
 *         product_id: "prod_xxxxxxxxxxxxx",
 *         app_id: "app_xxxxxxxxxxxxxx",
 *         created_before: "2023-12-01T05:00:00Z",
 *         created_after: "2023-12-01T05:00:00Z",
 *         account_id: "biz_xxxxxxxxxxxxxx"
 *     }
 */
export interface ListExperiencesRequest {
    /** Returns the elements in the list that come after the specified cursor. */
    after?: string;
    /** Returns the elements in the list that come before the specified cursor. */
    before?: string;
    /** Returns the first _n_ elements from the list. */
    first?: number;
    /** Returns the last _n_ elements from the list. */
    last?: number;
    /** Filter to only experiences attached to this product identifier. */
    product_id?: string;
    /** Filter to only experiences powered by this app identifier. */
    app_id?: string;
    /** Only return experiences created before this timestamp. */
    created_before?: string;
    /** Only return experiences created after this timestamp. */
    created_after?: string;
    /** The unique identifier of the company to list experiences for. */
    account_id: string;
}
