// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Whop from "../../../index.js";

export declare namespace TransfersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * A Transfer moves money between Whop balances: from one account or user to another, from an account's wallet to a person or address, or into a claim link anyone with the URL can redeem.
 *
 * Use the Transfers API to send money, find recipients you can pay, list and retrieve transfers when reconciling money movement, and preview or redeem claim links.
 *
 * Subscribe to `transfer.completed` and `transfer.failed` for outcomes instead of polling. Each participating account can subscribe to these events. `transfer.created` is also emitted on success, not when processing starts. A failed transfer can be retried under the same ID and later succeed; retrieve the transfer to reconcile its current status.
 *
 * A successful balance transfer credits the recipient's available balance unless a release date applies. Transfers funded from pending balance retain a release date and credit pending balance; applicable recipient reserves or fraud holds can keep funds unavailable. `succeeded` confirms the transfer completed, not that all funds are withdrawable.
 */
export class TransfersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TransfersClient.Options>;

    constructor(options: TransfersClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists the transfers you can see, sent or received, newest first by default. Optional account filters narrow the results.
     *
     * @param {Whop.ListTransfersRequest} request
     * @param {TransfersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.transfers.list()
     */
    public async list(
        request: Whop.ListTransfersRequest = {},
        requestOptions?: TransfersClient.RequestOptions,
    ): Promise<core.Page<Whop.ListTransfersResponse.Data.Item, Whop.ListTransfersResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Whop.ListTransfersRequest): Promise<core.WithRawResponse<Whop.ListTransfersResponse>> => {
                const {
                    origin_id: originId,
                    destination_id: destinationId,
                    order,
                    direction,
                    created_before: createdBefore,
                    created_after: createdAfter,
                    first,
                    after,
                    last,
                    before,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    origin_id: originId,
                    destination_id: destinationId,
                    order: order != null ? order : undefined,
                    direction: direction != null ? direction : undefined,
                    created_before: createdBefore,
                    created_after: createdAfter,
                    first,
                    after,
                    last,
                    before,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        "Api-Version-Date":
                            requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-10-09-2",
                        "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (
                                (await core.Supplier.get(this._options.environment)) ??
                                environments.WhopEnvironment.Production
                            ).api,
                        "transfers",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Whop.ListTransfersResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/transfers");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Whop.ListTransfersResponse.Data.Item, Whop.ListTransfersResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.page_info.end_cursor != null &&
                !(typeof response?.page_info.end_cursor === "string" && response?.page_info.end_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "after", response?.page_info.end_cursor));
            },
        });
    }

    /**
     * Moves money between Whop balances, sends USDT from an account's wallet, or funds a claim link anyone with the URL can redeem. The `type` you send decides which object comes back.
     *
     * @param {Whop.CreateTransfersRequestBody} request
     * @param {TransfersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.ConflictError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.transfers.create({
     *         type: "balance",
     *         amount: 25,
     *         currency: "usd",
     *         destination_id: "user_xxxxxxxxxxxxxx",
     *         origin_id: "biz_xxxxxxxxxxxxxx"
     *     })
     */
    public create(
        request: Whop.CreateTransfersRequestBody,
        requestOptions?: TransfersClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.CreateTransfersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Whop.CreateTransfersRequestBody,
        requestOptions?: TransfersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.CreateTransfersResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-10-09-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.WhopEnvironment.Production)
                        .api,
                "transfers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.CreateTransfersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Whop.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/transfers");
    }

    /**
     * Lists the people and accounts you can send money to from a balance. Pass a result's ID as `destination_id` when creating a transfer.
     *
     * @param {Whop.ListRecipientsTransfersRequest} request
     * @param {TransfersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.BadRequestError}
     * @throws {@link Whop.UnauthorizedError}
     * @throws {@link Whop.ForbiddenError}
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.transfers.listRecipients({
     *         origin_id: "origin_id"
     *     })
     */
    public async listRecipients(
        request: Whop.ListRecipientsTransfersRequest,
        requestOptions?: TransfersClient.RequestOptions,
    ): Promise<core.Page<Whop.ListRecipientsTransfersResponseDataItem, Whop.ListRecipientsTransfersResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Whop.ListRecipientsTransfersRequest,
            ): Promise<core.WithRawResponse<Whop.ListRecipientsTransfersResponse>> => {
                const { origin_id: originId, query, first, after } = request;
                const _queryParams: Record<string, unknown> = {
                    origin_id: originId,
                    query,
                    first,
                    after,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    mergeOnlyDefinedHeaders({
                        "Api-Version-Date":
                            requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-10-09-2",
                        "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
                    }),
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (
                                (await core.Supplier.get(this._options.environment)) ??
                                environments.WhopEnvironment.Production
                            ).api,
                        "transfers/recipients",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Whop.ListRecipientsTransfersResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Whop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                        case 401:
                            throw new Whop.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                        case 403:
                            throw new Whop.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 404:
                            throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                        default:
                            throw new errors.WhopError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/transfers/recipients");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Whop.ListRecipientsTransfersResponseDataItem, Whop.ListRecipientsTransfersResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.page_info.end_cursor != null &&
                !(typeof response?.page_info.end_cursor === "string" && response?.page_info.end_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "after", response?.page_info.end_cursor));
            },
        });
    }

    /**
     * Retrieves a single transfer.
     *
     * @param {Whop.RetrieveTransfersRequest} request
     * @param {TransfersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Whop.NotFoundError}
     * @throws {@link errors.WhopError}
     * @throws {@link errors.WhopTimeoutError}
     *
     * @example
     *     await client.transfers.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Whop.RetrieveTransfersRequest,
        requestOptions?: TransfersClient.RequestOptions,
    ): core.HttpResponsePromise<Whop.RetrieveTransfersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Whop.RetrieveTransfersRequest,
        requestOptions?: TransfersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Whop.RetrieveTransfersResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Api-Version-Date": requestOptions?.apiVersionDate ?? this._options?.apiVersionDate ?? "2026-10-09-2",
                "Idempotency-Key": requestOptions?.idempotencyKey ?? this._options?.idempotencyKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.WhopEnvironment.Production)
                        .api,
                `transfers/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Whop.RetrieveTransfersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Whop.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.WhopError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/transfers/{id}");
    }
}
