// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListPayoutsRequest {
    /** The owning account ID (a biz_ identifier). Provide this or user_id. */
    account_id?: string;
    /** The owning user ID (a user_ identifier). Provide this or account_id. */
    user_id?: string;
    /** Optional currency code filter, for example `usd`. */
    currency?: string;
    /** Filter to payouts whose `status` reads this word, matching exactly what this version displays — `reversed` finds settled payouts the bank later returned. Requires Api-Version-Date 2026-08-21 or later. */
    status?: Whop.ListPayoutsRequestStatus;
    /** Filter by how the payout was created. Payouts created before source tracking or through internal tooling carry no source and never match. */
    source?: Whop.ListPayoutsRequestSource;
    /** Filter to payouts sent to one saved payout method (a pytk_ identifier). An unknown id matches nothing. */
    payout_method_id?: string;
    /** Only payouts created before this ISO 8601 time (exclusive). */
    created_before?: string;
    /** Only payouts created at or after this ISO 8601 time (inclusive). */
    created_after?: string;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
    /** Number of results to return from the end of the range. */
    last?: number;
    /** Return results before this cursor. Use `page_info.start_cursor` from the previous response to fetch the previous page. */
    before?: string;
}
