// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RetrieveBusinessesRequest {
    /** The partner business ID (a coma_ identifier). */
    id: string;
}
