// This file was auto-generated by Fern from our API Definition.

export const ListCheckoutConfigurationsRequestOrder = {
    CreatedAt: "created_at",
} as const;
export type ListCheckoutConfigurationsRequestOrder =
    (typeof ListCheckoutConfigurationsRequestOrder)[keyof typeof ListCheckoutConfigurationsRequestOrder];
