// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ConfirmationTokensClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            account_id: "biz_xxxxxxxxxxxxxx",
            billing_details: {
                address: { city: "Austin", country: "US", line1: "123 Main St", postal_code: "78701" },
                email: "buyer@example.com",
                name: "Buyer Name",
            },
            payment_method: {
                card: { brand: "visa", last4: "4242", token_intent: "bt_ti_123" },
                category: "card",
                type: "card",
            },
            setup_future_usage: "off_session",
        };
        const rawResponseBody = {
            billing_details: {
                country: "AR",
                email: "marcus@shinetime.example",
                name: "Buyer Name",
                postal_code: "C1043",
            },
            created_at: "2026-01-01T12:00:00.000Z",
            expires_at: "2026-01-01T12:00:00.000Z",
            id: "ctok_xxxxxxxxxxxxxx",
            object: "confirmation_token",
            payment_method_preview: {
                bank_debit: { brand: "visa", last4: "4242" },
                card: { brand: "visa", last4: "4242" },
                category: "card",
                display_name: "Visa •••• 4242",
                id: "payt_xxxxxxxxxxxxxx",
                saved: { brand: "visa", last4: "4242" },
                type: "card",
                wallet: { brand: "visa", last4: "4242" },
            },
            setup_future_usage: "off_session",
            status: "pending",
        };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.confirmationTokens.create({
            account_id: "biz_xxxxxxxxxxxxxx",
            billing_details: {
                address: {
                    city: "Austin",
                    country: "US",
                    line1: "123 Main St",
                    postal_code: "78701",
                },
                email: "buyer@example.com",
                name: "Buyer Name",
            },
            payment_method: {
                card: {
                    brand: "visa",
                    last4: "4242",
                    token_intent: "bt_ti_123",
                },
                category: "card",
                type: "card",
            },
            setup_future_usage: "off_session",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", payment_method: { category: "card" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.create({
                account_id: "account_id",
                payment_method: {
                    category: "card",
                },
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", payment_method: { category: "card" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.create({
                account_id: "account_id",
                payment_method: {
                    category: "card",
                },
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", payment_method: { category: "card" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.create({
                account_id: "account_id",
                payment_method: {
                    category: "card",
                },
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", payment_method: { category: "card" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.create({
                account_id: "account_id",
                payment_method: {
                    category: "card",
                },
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", payment_method: { category: "card" } };
        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .post("/confirmation_tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.create({
                account_id: "account_id",
                payment_method: {
                    category: "card",
                },
            });
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            billing_details: {
                country: "AR",
                email: "marcus@shinetime.example",
                name: "Buyer Name",
                postal_code: "C1043",
            },
            created_at: "2026-01-01T12:00:00.000Z",
            expires_at: "2026-01-01T12:00:00.000Z",
            id: "ctok_xxxxxxxxxxxxxx",
            object: "confirmation_token",
            payment_method_preview: {
                bank_debit: { brand: "visa", last4: "4242" },
                card: { brand: "visa", last4: "4242" },
                category: "card",
                display_name: "Visa •••• 4242",
                id: "payt_xxxxxxxxxxxxxx",
                saved: { brand: "visa", last4: "4242" },
                type: "card",
                wallet: { brand: "visa", last4: "4242" },
            },
            setup_future_usage: "off_session",
            status: "pending",
        };

        server
            .mockEndpoint()
            .get("/confirmation_tokens/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.confirmationTokens.retrieve({
            id: "id",
            account_id: "account_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/confirmation_tokens/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.confirmationTokens.retrieve({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });
});
