// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    context: {
                        ad_campaign_id: "adcamp_xxxxxxxxxxxxxx",
                        ad_click_id: "IwAR123",
                        ad_click_type: "fbclid",
                        ad_id: "ad_xxxxxxxxxxxxxx",
                        ad_set_id: "adgrp_xxxxxxxxxxxxxx",
                        utm_campaign: "brand",
                        utm_content: "creative",
                        utm_medium: "paid",
                        utm_source: "google",
                        utm_term: "keyword",
                    },
                    currency: "usd",
                    custom_name: "coating_deposit_paid",
                    event_id: "evt_124",
                    event_name: "pixel.custom",
                    event_time: "2026-01-01T12:00:00Z",
                    id: "evt_124",
                    path: "/checkout/complete",
                    person_id: "prsn_123",
                    questions: [
                        {
                            answer: "SUV",
                            id: "q_2",
                            key: "vehicle_type",
                            options: ["Truck"],
                            question: "What vehicle are we detailing?",
                            type: "custom",
                        },
                    ],
                    recommended_action_chain_id: "recommended_action_chain_id",
                    recommended_action_shown_position: 1,
                    referrer_url: "https://google.com",
                    related: {
                        account: {
                            id: "biz_xxxxxxxxxxxxxx",
                            logo_url:
                                "https://whop-assets-example.s3.amazonaws.com/uploads/image/2026-01-01/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                            route: "biz_xxxxxxxxxxxxxx",
                            title: "Shine Time Auto Detailing",
                        },
                        ad: {
                            id: "ad_xxxxxxxxxxxxxx",
                            thumbnail_url:
                                "https://whop-assets-example.s3.amazonaws.com/uploads/image/2026-01-01/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                            title: "Ceramic coating — before/after reel",
                        },
                        ad_campaign: {
                            id: "adcamp_xxxxxxxxxxxxxx",
                            platform: "meta",
                            title: "Ceramic coating — spring push",
                        },
                        ad_group: { id: "adgrp_xxxxxxxxxxxxxx", title: "Austin — SUV owners" },
                        app: {
                            domain_id: "whopappdomain0000001",
                            icon_url:
                                "https://whop-assets-example.s3.amazonaws.com/uploads/image/2026-01-01/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                            id: "app_xxxxxxxxxxxxxx",
                            title: "Shine Time Booking",
                        },
                        audience: {
                            file_name: "shine-time-customers.csv",
                            id: "adaud_xxxxxxxxxxxxxx",
                            title: "Austin ceramic coating leads",
                        },
                        payment: {
                            card_brand: "visa",
                            card_last4: "4242",
                            id: "pay_xxxxxxxxxxxxxx",
                            provider: "stripe",
                        },
                        plan: {
                            billing_period: 30,
                            currency: "usd",
                            id: "plan_xxxxxxxxxxxxxx",
                            initial_price: 0,
                            renewal_price: 59,
                            title: "Unlimited Wash Club",
                        },
                        product: {
                            id: "prod_xxxxxxxxxxxxxx",
                            route: "ceramic-coating-package",
                            title: "Ceramic Coating Package",
                        },
                        user: {
                            avatar_url:
                                "https://whop-assets-example.s3.amazonaws.com/uploads/image/2026-01-01/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                            id: "user_xxxxxxxxxxxxxx",
                            name: "Dana Whitfield",
                            username: "danawhitfield",
                        },
                    },
                    total_usd_amount: 249,
                    url: "https://shinetime.example/checkout/complete",
                    user: {
                        city: "Austin",
                        country: "US",
                        email: "marcus@shinetime.example",
                        first_name: "Dana",
                        last_name: "Whitfield",
                        name: "Dana Whitfield",
                        phone: "5551234567",
                    },
                    value: 249,
                },
            ],
            page_info: {
                end_cursor: "cursor_end",
                has_next_page: false,
                has_previous_page: false,
                start_cursor: "cursor_start",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.events.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/events").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.list();
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/events").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.list();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "biz_xxxxxxxxxxxxxx", event_name: "coating_deposit_paid" };
        const rawResponseBody = { id: "evnt_xxxxxxxxxxxxxx" };

        server
            .mockEndpoint()
            .post("/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.create({
            account_id: "biz_xxxxxxxxxxxxxx",
            event_name: "coating_deposit_paid",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { account_id: "account_id", event_name: "event_name" };
        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .post("/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.create({
                account_id: "account_id",
                event_name: "event_name",
            });
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("pulse (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    event_name: "ledger_line.created",
                    event_time: "2026-01-01T12:00:00Z",
                    total_usd_amount: 45.5,
                    type: "purchase",
                    user: { city: "Austin", country: "US" },
                },
            ],
            page_info: {
                end_cursor: "cursor_end",
                has_next_page: true,
                has_previous_page: false,
                start_cursor: "cursor_start",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/events/pulse")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.events.pulse();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("pulse (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/events/pulse").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.pulse();
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("validatePixel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            firing_data_ok: true,
            host_events: ["lead"],
            installed: true,
            last_fired_days: { lead: 2 },
            last_seen_days: 2,
            native_tracking: false,
            page_events: ["lead"],
            reachable: true,
            url: "https://shinetime.example/checkout/complete",
        };

        server
            .mockEndpoint()
            .post("/events/validate_pixel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.events.validatePixel();
        expect(response).toEqual(rawResponseBody);
    });

    test("validatePixel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/events/validate_pixel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.validatePixel();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("validatePixel (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/events/validate_pixel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.validatePixel();
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("validatePixel (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/events/validate_pixel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.validatePixel();
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("validatePixel (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .post("/events/validate_pixel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.events.validatePixel();
        }).rejects.toThrow(Whop.ConflictError);
    });
});
