// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("LedgersClient", () => {
    test("getFinancialReport (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            beginning_balance: 11480.02,
            ending_balance: 23750.55,
            fx_excluded_currencies: ["ngn"],
            report_type: "balance_summary",
            rows: [
                {
                    account_ik_path: "assets/wallets/wallet/available",
                    account_name: "Available balance",
                    account_type: "asset",
                    amount: 23750.55,
                    grouping: "advertising",
                    line_category: "accelerated_settlement_fee",
                    line_count: 214,
                    period: "2026-05",
                    profit_and_loss_section: "revenue",
                },
            ],
            total: 23750.55,
        };

        server.mockEndpoint().get("/financial_reports").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ledgers.getFinancialReport({
            account_id: "account_id",
            report_type: "balance_summary",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getFinancialReport (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/financial_reports").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ledgers.getFinancialReport({
                account_id: "account_id",
                report_type: "balance_summary",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("getFinancialReport (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/financial_reports").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ledgers.getFinancialReport({
                account_id: "account_id",
                report_type: "balance_summary",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("getFinancialReport (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/financial_reports").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ledgers.getFinancialReport({
                account_id: "account_id",
                report_type: "balance_summary",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("getFinancialReport (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/financial_reports").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ledgers.getFinancialReport({
                account_id: "account_id",
                report_type: "balance_summary",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });
});
