// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PartnersClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = {
            referral_link: "https://whop.com/network/",
            whop_partner_enabled_at: "2026-01-01T12:00:00Z",
        };

        server.mockEndpoint().post("/partners").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.partners.create();
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/partners").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.create();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/partners").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.create();
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { error: { message: "message", type: "type" } };

        server.mockEndpoint().post("/partners").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.create();
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("leaderboard (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = {
            leaders: [
                {
                    first_referral_started_at: "2026-01-01T12:00:00Z",
                    rank: 1,
                    total_earnings_usd: "100.00",
                    total_volume_usd: "0.00",
                    user: {
                        city: "Austin",
                        country: "US",
                        id: "user_xxxxxxxxxxxxxx",
                        name: "Marcus Webb",
                        profile_picture: { url: "https://ui-avatars.com/api/" },
                        username: "marcuswebb",
                    },
                },
            ],
            me: {
                first_referral_started_at: "2026-01-01T12:00:00Z",
                rank: 2,
                total_earnings_usd: "4.00",
                total_volume_usd: "40.00",
                user: {
                    city: "Austin",
                    country: "US",
                    id: "user_xxxxxxxxxxxxxx",
                    name: "Marcus Webb",
                    profile_picture: { url: "https://ui-avatars.com/api/" },
                    username: "marcuswebb",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/partners/leaderboard")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.partners.leaderboard();
        expect(response).toEqual(rawResponseBody);
    });

    test("leaderboard (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/partners/leaderboard")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.partners.leaderboard();
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("referredUsers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = {
            data: [
                {
                    business_count: 1,
                    earnings: { amount: "-2.50", currency: "usd", decimals: 2, display_decimals: 2 },
                    joined_at: "2026-01-01T12:00:00Z",
                    total_earnings_usd: "10.00",
                    total_volume_usd: "100.00",
                    user: {
                        city: "Austin",
                        country: "US",
                        email: "marcus@shinetime.example",
                        id: "user_xxxxxxxxxxxxxx",
                        name: "Tanya Cole",
                        profile_picture: { url: "https://ui-avatars.com/api/" },
                        username: "tanyacole",
                    },
                    volume_30d: { amount: "-2.50", currency: "usd", decimals: 2, display_decimals: 2 },
                },
            ],
            page_info: {
                end_cursor: "end_cursor",
                has_next_page: false,
                has_previous_page: false,
                start_cursor: "WyJjdXJzb3IiLDFd",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/partners/referred_users")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.partners.referredUsers();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("referredUsers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/partners/referred_users")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.partners.referredUsers();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = {
            certification_complete: false,
            joined_at: "2026-01-01T12:00:00.000Z",
            payout_rates: [
                {
                    duration: { unit: "day", value: 600 },
                    rates: [{ income_source: "sales", percentage: 10 }],
                    tier: "first",
                },
            ],
            referred_businesses_count: 1,
            user: {
                id: "user_xxxxxxxxxxxxxx",
                name: "Dana Whitfield",
                profile_picture: { url: "https://ui-avatars.com/api/" },
                username: "danawhitfield",
            },
            verification_waitlist_joined: false,
            whop_partner_verified_at: "whop_partner_verified_at",
        };

        server.mockEndpoint().get("/partners/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.partners.retrieve({
            id: "me",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/partners/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/partners/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: { api: server.baseUrl, vault: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/partners/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.partners.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });
});
