// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ReactionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    emoji: ":heart:",
                    id: "reac_xxxxxxxxxxxxxxxxxxxxxx",
                    resource_id: "resource_id",
                    user: { id: "user_xxxxxxxxxxxxx", name: "John Doe", username: "johndoe42" },
                },
            ],
            page_info: {
                end_cursor: "end_cursor",
                has_next_page: true,
                has_previous_page: true,
                start_cursor: "start_cursor",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/reactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.reactions.list({
            first: 42,
            last: 42,
            resource_id: "resource_id",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.UnprocessableEntityError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.list({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = {
            emoji: ":heart:",
            id: "reac_xxxxxxxxxxxxxxxxxxxxxx",
            resource_id: "resource_id",
            user: { id: "user_xxxxxxxxxxxxx", name: "John Doe", username: "johndoe42" },
        };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.reactions.create({
            resource_id: "resource_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/reactions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.reactions.create({
                resource_id: "resource_id",
            });
        }).rejects.toThrow(Whop.InternalServerError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            emoji: ":heart:",
            id: "reac_xxxxxxxxxxxxxxxxxxxxxx",
            resource_id: "resource_id",
            user: { id: "user_xxxxxxxxxxxxx", name: "John Doe", username: "johndoe42" },
        };

        server
            .mockEndpoint()
            .get("/reactions/reac_xxxxxxxxxxxxxxxxxxxxxx")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.reactions.retrieve({
            id: "reac_xxxxxxxxxxxxxxxxxxxxxx",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnprocessableEntityError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.TooManyRequestsError);
    });

    test("retrieve (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/reactions/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.retrieve({
                id: "id",
            });
        }).rejects.toThrow(Whop.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = true;

        server
            .mockEndpoint()
            .delete("/reactions/reac_xxxxxxxxxxxxxxxxxxxxxx")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.reactions.delete({
            id: "reac_xxxxxxxxxxxxxxxxxxxxxx",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnprocessableEntityError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.TooManyRequestsError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/reactions/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.reactions.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.InternalServerError);
    });
});
