// This file was auto-generated by Fern from our API Definition.

import * as Whop from "../../src/api/index";
import { WhopClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SocialAccountsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    error: "You don't have permission to share this account. Ask an admin of its Meta Business Portfolio to grant you full control, then share it again.",
                    external_id: "1234567891",
                    id: "sacc_xxxxxxxxxxxxxx",
                    name: "Shine Time Auto Detailing",
                    parent_social_account: {
                        external_id: "555111",
                        id: "sacc_xxxxxxxxxxxxxx",
                        name: "Shine Time Auto Detailing",
                        platform: "x",
                        profile_picture_url: "https://shinetime.example/logo.png",
                        username: "shinetimedetailing",
                        verified: true,
                    },
                    platform: "x",
                    profile_picture_url: "https://shinetime.example/logo.png",
                    scopes: ["advertise"],
                    url: "https://instagram.com/shinetimedetail",
                    username: "shinetimedetail",
                    verified: true,
                },
            ],
            page_info: {
                end_cursor: "WyJjdXJzb3IiLDFd",
                has_next_page: false,
                has_previous_page: false,
                start_cursor: "WyJjdXJzb3IiLDFd",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/social_accounts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.socialAccounts.list();

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/social_accounts").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.socialAccounts.list();
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/social_accounts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.socialAccounts.list();
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "facebook" };
        const rawResponseBody = {
            error: "You don't have permission to share this account. Ask an admin of its Meta Business Portfolio to grant you full control, then share it again.",
            external_id: "1234567891",
            id: "sacc_xxxxxxxxxxxxxx",
            name: "Shine Time Auto Detailing",
            parent_social_account: {
                external_id: "555111",
                id: "sacc_xxxxxxxxxxxxxx",
                name: "Shine Time Auto Detailing",
                platform: "x",
                profile_picture_url: "https://shinetime.example/logo.png",
                username: "shinetimedetailing",
                verified: true,
            },
            platform: "x",
            profile_picture_url: "https://shinetime.example/logo.png",
            scopes: ["advertise"],
            url: "https://instagram.com/shinetimedetail",
            username: "shinetimedetail",
            verified: true,
        };

        server
            .mockEndpoint()
            .post("/social_accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.socialAccounts.create({
            platform: "facebook",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "facebook" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/social_accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.create({
                platform: "facebook",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "facebook" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/social_accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.create({
                platform: "facebook",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "facebook" };
        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .post("/social_accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.create({
                platform: "facebook",
            });
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("connect (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            platform: "meta_business",
            redirect_url: "https://example.com/settings/social-accounts",
        };
        const rawResponseBody = { authorize_url: "https://www.facebook.com/v25.0/dialog/oauth" };

        server
            .mockEndpoint()
            .post("/social_accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.socialAccounts.connect({
            platform: "meta_business",
            redirect_url: "https://example.com/settings/social-accounts",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("connect (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "meta_business", redirect_url: "redirect_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/social_accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.connect({
                platform: "meta_business",
                redirect_url: "redirect_url",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("connect (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "meta_business", redirect_url: "redirect_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/social_accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.connect({
                platform: "meta_business",
                redirect_url: "redirect_url",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("connect (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { platform: "meta_business", redirect_url: "redirect_url" };
        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .post("/social_accounts/connect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.connect({
                platform: "meta_business",
                redirect_url: "redirect_url",
            });
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { deleted: true, id: "sacc_xxxxxxxxxxxxxx" };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.socialAccounts.delete({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: { message: "message", type: "type" } };

        server
            .mockEndpoint()
            .delete("/social_accounts/id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.delete({
                id: "id",
            });
        }).rejects.toThrow(Whop.ConflictError);
    });

    test("leadForms (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    completion: {
                        button_text: "See our work",
                        description: "We book coatings two days out, so pick a slot when we ring.",
                        headline: "Thanks — we will call you today",
                        url: "https://shinetime.example/gallery",
                    },
                    created_at: "2026-01-01T12:00:00.000Z",
                    disclaimer: {
                        body: "Ceramic coating requires the vehicle for two days.",
                        checkboxes: [{ checked_by_default: false, key: "consent_1", required: true, text: "I agree" }],
                        title: "Before you submit",
                    },
                    form_type: "more_volume",
                    id: "24839",
                    intro: {
                        description: "Tell us about your vehicle and we will send a fixed price.",
                        headline: "Get a ceramic coating quote",
                    },
                    locale: "en_US",
                    name: "Ceramic coating quote requests",
                    privacy_policy_link_text: "Shine Time privacy policy",
                    privacy_policy_url: "https://shinetime.example/privacy",
                    question_labels: ["Email"],
                    questions: [
                        {
                            format: "multiple_choice",
                            label: "What vehicle are we detailing?",
                            options: [
                                {
                                    key: "ceramic_coating",
                                    logic: {
                                        action: "go_to_question",
                                        target_end_page_index: 0,
                                        target_question_index: 3,
                                    },
                                    value: "Ceramic coating",
                                },
                            ],
                            type: "custom",
                        },
                    ],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/social_accounts/id/lead_forms")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.socialAccounts.leadForms({
            id: "id",
            account_id: "account_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("leadForms (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/lead_forms")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.leadForms({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("leadForms (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/lead_forms")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.leadForms({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("leadForms (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/lead_forms")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.leadForms({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });

    test("posts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    call_to_action: "learn_more",
                    destination_url: "https://shinetime.example/book",
                    embed_url: "https://www.facebook.com/plugins/post.php",
                    id: "media_1",
                    media_url: "https://shinetime.example/ceramic-coating-reel.mp4",
                    restrictions: ["lead_form_ineligible"],
                    thumbnail_url: "https://shinetime.example/ceramic-coating-poster.jpg",
                },
            ],
            page_info: { end_cursor: "MTI=", has_next_page: true },
        };

        server
            .mockEndpoint({ once: false })
            .get("/social_accounts/id/posts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.socialAccounts.posts({
            id: "id",
            account_id: "account_id",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("posts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/posts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.posts({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.BadRequestError);
    });

    test("posts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/posts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.posts({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.UnauthorizedError);
    });

    test("posts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WhopClient({
            maxRetries: 0,
            token: "test",
            apiVersionDate: "test",
            idempotencyKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/social_accounts/id/posts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.socialAccounts.posts({
                id: "id",
                account_id: "account_id",
            });
        }).rejects.toThrow(Whop.NotFoundError);
    });
});
