// This file was auto-generated by Fern from our API Definition.

export const ListAppsRequestAppType = {
    B2BApp: "b2b_app",
    B2CApp: "b2c_app",
    CompanyApp: "company_app",
    Component: "component",
    Website: "website",
} as const;
export type ListAppsRequestAppType = (typeof ListAppsRequestAppType)[keyof typeof ListAppsRequestAppType];
