// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateDomainsRequest {
    /** Domain ID, prefixed `dom_`. To retrieve, you can pass a hostname such as `example.com` instead; a bare name looks up `.com`. */
    id: string;
    /** App ID, prefixed app_. Must belong to the same account. */
    app_id?: string;
    /** Replacement custom string keys and values. */
    metadata?: Record<string, string>;
}
