// This file was auto-generated by Fern from our API Definition.

import type * as Whop from "../../../../../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListTopicsRequest {
    /** Only return preferences for this delivery channel (or not narrowed to a channel). */
    channel?: Whop.users.preferences.notifications.ListTopicsRequestChannel;
    /** Only return preferences scoped to this account's member notifications (`biz_` tag). */
    account_id?: string;
    /** Only return preferences scoped to this account's team notifications (`biz_` tag). */
    team_account_id?: string;
    /** Only return preferences scoped to this experience (`exp_` tag). */
    experience_id?: string;
    /** Only return preferences scoped to this notification topic (`topic_` tag). */
    topic_id?: string;
    /** Number of results to return from the start of the range. */
    first?: number;
    /** Return results after this cursor. Use `page_info.end_cursor` from the previous response to fetch the next page. */
    after?: string;
}
