// This file was auto-generated by Fern from our API Definition.

export const ListAdCampaignsRequestOrder = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
    Spend: "spend",
    Impressions: "impressions",
    Reach: "reach",
    Clicks: "clicks",
    UniqueClicks: "unique_clicks",
    Frequency: "frequency",
    ClickThroughRate: "click_through_rate",
    Results: "results",
    CostPerMille: "cost_per_mille",
    CostPerClick: "cost_per_click",
    CostPerResult: "cost_per_result",
    ReturnOnAdSpend: "return_on_ad_spend",
} as const;
export type ListAdCampaignsRequestOrder =
    (typeof ListAdCampaignsRequestOrder)[keyof typeof ListAdCampaignsRequestOrder];
