// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RetrieveBountySubmissionsRequest {
    /** The bounty submission to act on (`btys_` tag). */
    id: string;
}
